### PR TITLE
Fix mouse capture bug that affects pedestrian mode.

### LINKED ISSUE #6935: Pedestrian mode - mouse capture bug
When using the pedestrian mode, sometimes the mouse down behaviour will revert to the normal camera movement.

- Go to http://ci.terria.io/main/
- 3d mode
- Activate pedestrian mode
- Press "space" for a few seconds to increase the height of the camera
- Click on the terrain and drag mouse down the screen
- Observe that the camera starts to move along the terrain (as it does when pedestrian mode is not active)
- Instead, the camera should just tilt down without changing position

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

Fixes #6935 

[This PR](https://github.com/TerriaJS/terriajs/pull/6841) fixed the broken interaction for dragging points drawn on the map by making `DragPoints.js` work in v8. But the way `MeasureTool`, `UserDrawing` and `DragPoints` work, it always captures the mouse down and mouse up events even when the `MeasureTool` is not active.

This PR fixes the mouse capture problem by making sure `DragPoints` is activated only when a `UserDrawing` is activated.

### Test me

- Follow the steps in the [issue](https://github.com/TerriaJS/terriajs/issues/6935) to reproduce the error in [main](http://ci.terria.io/main/#share=s-dIDM45olteiauOppxXnsY9mTG7C&clean&https://gist.githubusercontent.com/na9da/737c818d6ca2ee0d22147181ae6eba0c/raw/9bd838001fd5820e65791a8e0892d29fa6005f92/melb-central-ion.json).
- The main thing you are looking for is the camera jumping around a bit instead of smoothly animating when you press down the mouse and drag it around.
- Make sure it is fixed in the [PR branch](http://ci.terria.io/fix-pedestrian/#share=s-dIDM45olteiauOppxXnsY9mTG7C&clean&https://gist.githubusercontent.com/na9da/737c818d6ca2ee0d22147181ae6eba0c/raw/9bd838001fd5820e65791a8e0892d29fa6005f92/melb-central-ion.json).

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/UserDrawing.ts [hunk 1]
```diff
@@ -150,14 +152,6 @@ export default class UserDrawing extends MappableMixin(
...
     this.invisible = options.invisible;
-
-    // helper for dragging points around
-    this.dragHelper = new DragPoints(options.terria, (customDataSource) => {
-      if (typeof this.onPointMoved === "function") {
-        this.onPointMoved(customDataSource);
-      }
-      this.prepareToAddNewPoint();
-    });
   }
```
Comment (na9da) [inline lib/Models/UserDrawing.ts:155]: Instead of creating the `dragHelper` in the constructor, we will create it only when the `UserDrawing` is activated. This makes sure that the `dragHelper` will capture mouse only when it is being used.

**Review by staffordsmith83 — APPROVED** [review]
Looks good, tested and code inspected.
