### PR TITLE
Fix CKAN naming

### LINKED ISSUE #4903: Investigate naming of CKAN dynamic items in version 8
CKAN group seems to name it's items by CKAN Dataset instead of Resource.

- [x] Investigate why this is happening on http://pacificmap.prod.saas.terria.io/#share=s-600IuxFH0DlYfU0Gjspb88pe7Dm
- [x] Fix ASAP

image

### PR DESCRIPTION
**Pull request by tephenavies**
### What this PR does

Fixes #4903.

Add a stratum of computeds so that CkanItemReference inherits shared traits from a containing CkanCatalogGroup

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: lib/Models/CkanItemReference.ts [hunk 1]
```diff
@@ -124,16 +127,16 @@ export class CkanDatasetStratum extends LoadableStratum(
...
-        return this.ckanDataset.title + " - " + this.ckanResource.format;
+        return this.ckanDataset.title + " - " + this.ckanResource.name;
       }
       if (
-        this.ckanItemReference.useCombinationNameWhereMultipleResources &&
+        this.ckanItemReference.useDatasetNameAndFormatWhereMultipleResources &&
         this.ckanDataset.resources.length > 1
       ) {
-        return this.ckanDataset.title + " - " + this.ckanResource.name;
+        return this.ckanDataset.title + " - " + this.ckanResource.format;
```
Comment (tephenavies) [inline lib/Models/CkanItemReference.ts:145]: Switched the order that these are checked so the default is checked last. Otherwise setting `useCombinationNameWhereMultipleResources` without setting `useDatasetNameAndFormatWhereMultipleResources` to false doesn't do anything

Comment (soyarsauce) [reply lib/Models/CkanItemReference.ts:145]: This would better be inline comments in ckanitemreference so it's not lost to the PR

**Review by soyarsauce — APPROVED** [review]
image

Merging as code commit changed passed
