### PR TITLE
Give a drag'n'dropped file a name in the workbench

### LINKED ISSUE #3399: DragDrop CSVs appear as 'unnamed item'
**Steps to reproduce**
1. Navigate to http://ci.terria.io/master/
2. Drag CSV onto map (eg. "Population Estimates 2017-18.csv")
3. See "unnamed item" in workbench

### PR DESCRIPTION
**Pull request by rowanwins**
Resolves #3399 by giving a drag'n'dropped item it's filename as the name in the workbench

### CODE REVIEW

File: lib/Models/createCatalogItemFromFileOrUrl.js [hunk 1]
```diff
@@ -156,6 +156,7 @@ function loadItem(newCatalogItem, name, fileOrUrl) {
     newCatalogItem.data = fileOrUrl;
     newCatalogItem.dataSourceUrl = fileOrUrl.name;
     newCatalogItem.dataUrlType = "local";
+    newCatalogItem.name = fileOrUrl.name;
```
Comment (kring) [inline lib/Models/createCatalogItemFromFileOrUrl.js:159]: Does this work if `fileOrUrl` is a URL? I wouldn't think it would have a name property.

**Comment by kring** [comment]
Please update CHANGES.md as well.

File: lib/Models/createCatalogItemFromFileOrUrl.js (hunk 1 above)
Comment (rowanwins) [reply lib/Models/createCatalogItemFromFileOrUrl.js:159]: This change only effects files - the [if/else statement above](https://github.com/TerriaJS/terriajs/pull/3584/files/44c73e6560d91f41a3f5d277014489c0095007e7#diff-45581fa26beec87f4e76b259504095bcL153) basically means this block only gets applied to files.

**Review by tephenavies — APPROVED** [review]
