### PR TITLE
Fix sharing when using initfile.

### LINKED ISSUE #7269: Share using initfile
If you generate a share URL from a map that uses parameters in the URL, for example, an `initfile`, those parameters are lost. It should be kept, at least in the case of an `initfile`, otherwise, some data could become unreachable.

### PR DESCRIPTION
**Pull request by glughi**
### What this PR does

Fixes #7269 
Replace PR #7270 

### Test me
Using, ie, `https://terriamap.com/#emg202305`, you can load some data from `emg202305.json`.
Without this fix, the sharing link from `https://terriamap.com/#emg202305` will be something like 
https://terriamap.com/#share=g-8feface8fefd6fe09ac81f22f21ec5d8
so you can't reload data from `emg202305.json`.
Instead, with this fix, the link will be something like
https://terriamap.com/#emg202305&share=g-8feface8fefd6fe09ac81f22f21ec5d8

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/ReactViews/Map/Panels/SharePanel/BuildShareLink.ts [hunk 1]
```diff
@@ -40,6 +40,16 @@ function buildBaseShareUrl(
 ) {
   const uri = new URI(document.baseURI).fragment("").search("");
 
+  const usefulSubs = new URL(document.URL).hash
```
Comment (niktayv) [inline lib/ReactViews/Map/Panels/SharePanel/BuildShareLink.ts]: Can we find a more descriptive name for this variable?

**Comment by niktayv** [comment]
It would be helpful to describe how to test this feature.
Is there a minimal way to reproduce a failure?

**Comment by niktayv** [comment]
By the way, I inspected the CI/build failure that occurs at `yarn gulp test-firefox`.
Locally, this test passes, so I asked the core team to help resolve this issue.

**Comment by glughi** [comment]
Updated.

**Review by na9da — APPROVED** [review]
LGTM. Thanks @glughi
