### PR TITLE
Mobx: Fix display of projected coordinates in LocationBar

### LINKED ISSUE #3891: Changing coord presentation fails in mobx
Clicking on the coord bar in a mobx app doesn't do anything. Throws an error related to `toggleUseProjection` method.

Coords

### PR DESCRIPTION
**Pull request by rowanwins**
Fixes when you click on the LocationBar - now it correctly shows the projected coordinates.

Resolves #3891

### CODE REVIEW

File: lib/ReactViews/Map/Legend/LocationBar.jsx [hunk 1]
```diff
@@ -23,7 +24,9 @@ const LocationBar = observer(
     },
 
     toggleUseProjection() {
-      this.props.mouseCoords.toggleUseProjection();
+      runInAction(() => {
```
Comment (na9da) [inline lib/ReactViews/Map/Legend/LocationBar.jsx]: Just a small nitpick - It might be better to wrap `MouseCoords.toggleUseProjection` with an `@action` decorator instead.
