### PR TITLE
Set default orientation for GLTFs to zero degrees HPR.

### LINKED ISSUE #5690: Use 0 default rotation for GltfCatalogItem
Currently when no rotation is specified for a GltfCatalogItem, the orientation of the model is wrong as shown in the screenshot below. 

This is because we default to a `Quaternion.IDENTITY` rotation instead of `HPR=(0,0,0)`:

https://github.com/TerriaJS/terriajs/blob/cb56deb620b8268a6c42e23d4ef273e8a65e77f6/lib/Models/GltfCatalogItem.ts#L86-L89

image

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

Fixes #5690 

Sets the default orientation for `GltfCatalogItem` to 0 wrt ENU so that it is aligned correctly to the ground at its origin location.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: test/Models/GltfCatalogItemSpec.ts [hunk 1]
```diff
@@ -28,18 +36,27 @@ describe("GltfCatalogItem", function() {
...
-          expect(orientation.x).toEqual(0);
-          expect(orientation.y).toEqual(0);
-          expect(orientation.z).toEqual(0);
-          expect(orientation.w).toEqual(1);
+        if (orientation !== undefined) {
+          const { heading, pitch, roll } = getEntityHprInDegrees(entity);
+          expect(heading).toEqual(0);
+          expect(pitch).toEqual(0);
+          expect(roll).toEqual(0);
         }
```
Comment (na9da) [inline test/Models/GltfCatalogItemSpec.ts:60]: Refactored the test so that we directly check the HPR values in degrees.

**Review by KeyboardSounds — APPROVED** [review]
Thanks Nanda!
