### PR TITLE
fix basemaps ordering

### LINKED ISSUE #7169: Basemaps sorting bug
If you use `enabledBaseMaps`, basemaps should appear in _MapSettings_ in the order established in the array.

```
"enabledBaseMaps": [
      "basemap-dbtr-web",
      "basemap-dbtr-ctr",
      "basemap-dbtr-orto2018",
      "basemap-agea-2020",
      "basemap-orto-2018",
      "basemap-agea-2011",
      "basemap-bing-aerial-with-labels",
      "bing-aerial",
      "osm",
      "basemap-positron",
      "basemap-darkmatter",
      "white"
],
```

How it should be
image

and how it is
image

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #7169 

Supersedes the #7170 since there was no feedback on it by PR author.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/BaseMaps/BaseMapsModel.ts [hunk 1]
```diff
@@ -52,20 +51,26 @@ export class BaseMapsModel extends CreateModel(BaseMapsTraits) {
...
+        ?.map((enabledBaseMapId) => {
+          return this.items.find((item) => item.item === enabledBaseMapId);
+        })
+        .filter(isDefined) ?? this.items;
+
+    baseMapItems.forEach((baseMapItem) => {
+      if (baseMapItem.item && !ModelReference.isRemoved(baseMapItem.item)) {
+        const itemModel = this.terria.getModelById(
+          BaseModel,
+          String(baseMapItem.item)
```
Comment (na9da) [inline lib/Models/BaseMaps/BaseMapsModel.ts]: Doubt: What's the reason we need to wrap with `String()` here?

File: CHANGES.md [hunk 2]
```diff
@@ -38,13 +38,13 @@
...
 - Move GeoJSON helper functions (`isFeatureCollection` etc) to `lib/Core/GeoJson.ts`
 - Split up `ArcGisFeatureServerCatalogItem` into `ArcGisFeatureServerStratum` and `esriStyleToTableStyle`
-
 - Remove unused pmtiles dependency.
 - Update data styling docs
 - Remove unused babel/eslint-parser dependency.
 - Hide 'Story' button in mobile view if story panel is active.
 - Update empty workbench help text
 - Remove unused `arraysAreEqual`, `autoUpdate`, `flattenNested`, `freezeInDebug`, `isPromise`, `loadJsonp`, `OrUndefined`, and `superGet` files from lib/Core.
+- Fix basemaps order
```
Comment (na9da) [inline CHANGES.md]: Suggestion: It might be good to add that it now follows the order given by `enabledBaseMaps` setting.

**Review by na9da — APPROVED** [review]
@zoran995 - LGTM.
Just a couple of comments.

File: lib/Models/BaseMaps/BaseMapsModel.ts (hunk 1 above)
Comment (zoran995) [reply lib/Models/BaseMaps/BaseMapsModel.ts]: no reason, forgot to remove it

File: CHANGES.md (hunk 2 above)
Comment (zoran995) [reply CHANGES.md]: done
