### PR TITLE
Fix issue #5331.

### LINKED ISSUE #5331: CkanCatalogGroup should handle filterQuery correctly
The current implementation assumes that each element in filterQuery array of CkanCatalogGroup is an Object that has key-value pair such as
```
{
  "fq": "(organization:alpine-shire-council AND res_format:(geojson OR GeoJSON OR kml OR KML OR kmz OR KMZ OR wms OR WMS OR CSV-GEO-AU OR csv-geo-au OR aus-geo-csv OR \"Esri REST\"))"
}
```

However, an array element can also be a pure query string such as 
```
  "fq=+(res_format%3Awms%20OR%20res_format%3AWMS)"
```
The code should also handle that case.

### PR DESCRIPTION
**Pull request by mwu2018**
### What this PR does

Fixes #5331 

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: lib/Models/CkanCatalogGroup.ts [hunk 1]
```diff
@@ -84,9 +84,13 @@ export class CkanServerStratum extends LoadableStratum(CkanCatalogGroupTraits) {
         .segment("api/3/action/package_search")
         .addQuery({ start: 0, rows: 1000, sort: "metadata_created asc" });
 
-      Object.keys(filterQuery).forEach((key: string) =>
-        uri.addQuery(key, filterQuery[key])
-      );
+      if (filterQuery.toString().includes("fq=")) {
+        uri.query(uri.query() + "&" + filterQuery.toString());
+      } else {
```
Comment (nf-s) [inline lib/Models/CkanCatalogGroup.ts]: If the `filterQuery` trait can have string elements, it needs to be reflected in the `Trait`

https://github.com/TerriaJS/terriajs/blob/6e4d4df9dc368b155d283abd48bbe0c788960616/lib/Traits/CkanCatalogGroupTraits.ts#L25-L43

Comment (nf-s) [reply lib/Models/CkanCatalogGroup.ts]: At the moment it only allows `JsonObject` elements

Comment (nf-s) [reply lib/Models/CkanCatalogGroup.ts]: A possible change could be:
```ts
  filterQuery?: {
    [key: string]: JsonValue | string;
  }[]
```

**Review by nf-s — CHANGES_REQUESTED** [review]

File: lib/Models/CkanCatalogGroup.ts (hunk 1 above)
Comment (mwu2018) [reply lib/Models/CkanCatalogGroup.ts]: If `filterQuery` can only have `JsonObject` elements. An element like "fq=+blahblah" is considered valid JsonObject.

Comment (mwu2018) [reply lib/Models/CkanCatalogGroup.ts]: E.g.  filterQuery?: Object[] = ["fq=+blahblah"];

Therefore I don't think the Trait needs to be changed. @nf-s

Comment (nf-s) [reply lib/Models/CkanCatalogGroup.ts]: String isn't a valid JsonObject;

```
export interface JsonObject {
  [key: string]: JsonValue;
}
```

But I just realised that my suggestion is totally wrong! I meant something like this:

```ts
filterQuery?: JsonObject[] | string[] = [
    "Some string",
    {
      fq:
        '(res_format:(czml OR CZML OR geojson OR GeoJSON OR WMS OR wms OR kml OR KML OR kmz OR KMZ OR WFS OR wfs OR CSV-GEO-AU OR csv-geo-au OR "Esri REST"))'
    }
  ];
```

Comment (nf-s) [reply lib/Models/CkanCatalogGroup.ts]: ~But also, why do we need a `string`?~
 
~Isn't `["fq=+blahblah"]` equivalent to `{fq: "blahblah"}`~

Never mind, just realised master supports this

Comment (mwu2018) [reply lib/Models/CkanCatalogGroup.ts]: @nf-s You are right. I made a mistake by using Object instead of JsonObject in the example
 ```filterQuery?: Object[] = ["fq=+blahblah"];```
which is valid but useless. Has adopted your recommendation, which will cause other improvement. See the new commit.

File: lib/Models/CkanCatalogGroup.ts [hunk 2]
```diff
@@ -84,9 +85,13 @@ export class CkanServerStratum extends LoadableStratum(CkanCatalogGroupTraits) {
         .segment("api/3/action/package_search")
         .addQuery({ start: 0, rows: 1000, sort: "metadata_created asc" });
 
-      Object.keys(filterQuery).forEach((key: string) =>
-        uri.addQuery(key, filterQuery[key])
-      );
+      if (typeof filterQuery === "string") {
+        uri.query(uri.query() + "&" + filterQuery.toString());
```
Comment (nf-s) [inline lib/Models/CkanCatalogGroup.ts]: Looks good @mwu2018 
Sorry to nitpick, but is it possible to use `uri.addQuery()` instead of `uri.query(uri.query() + ...`?

**Review by nf-s — CHANGES_REQUESTED** [review]

File: lib/Models/CkanCatalogGroup.ts (hunk 2 above)
Comment (mwu2018) [reply lib/Models/CkanCatalogGroup.ts]: @nf-s You did not nitpick at all. Instead, you have opened a can of worms 😃 
1. The `filterQuery` trait is changed similar to what you suggested initially. Your later suggestion does not allow mixed elements in the array. 
2. We can not use `uri.addQuery(filterQuery)` because the URI encoder will escape `=`, which is not what we want. I have added some comments in the code.
3. The code is slightly refactored in order to do simple unit tests.

Can you please take another look?

**Review by nf-s — APPROVED** [review]
