### PR TITLE
Fix difftool, TSify a bunch of components.

### LINKED ISSUE #6278: DEA Difference Tool doesn't load, errors
When trying to use the DEA Difference Tool it doesn't work at the moment, it just immediately errors before actually starting:

Screen Shot 2022-05-02 at 14 29 01

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

Fixes #6278 

Changes:
- Fixes broken `DiffTool` due to referencing an invalid react portal id.
- Fix dodgy `DiffTool` behavior which removed all timeline elements when entering difftool. Instead we now simply hide the timeline.
- TSify `BottomDock` and `measureElement`
  
### Test me
  
- Open [CI link for this branch](http://ci.terria.io/fix-difftool/#share=s-4rC0JgpOAWRf15WGN9bBmpXfmS4&clean&https://gist.githubusercontent.com/na9da/afa45da8c661959383606b33046358bd/raw/0f4f59317c565ef0719805daa1f15de3afefb789/delta.json).
- From the `...` menu for the workbench item select `Difference`
- Previously, an error gets thrown (check: [main branch CI link](http://ci.terria.io/main/#share=s-4rC0JgpOAWRf15WGN9bBmpXfmS4&clean&https://gist.githubusercontent.com/na9da/afa45da8c661959383606b33046358bd/raw/0f4f59317c565ef0719805daa1f15de3afefb789/delta.json))
- Now, the difftool should open correctly

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/ReactViews/Workbench/Controls/ViewingControls.tsx [hunk 1]
```diff
@@ -269,9 +269,6 @@ class ViewingControls extends React.Component<
   }
 
   openDiffTool() {
-    // Disable timeline
-    // Should we do this? Difference is quite a specific use case
-    this.props.item.terria.timelineStack.removeAll();
```
Comment (na9da) [inline lib/ReactViews/Workbench/Controls/ViewingControls.tsx:274]: This was a dodgy behavior which resulted in losing timeline items when entering and leaving difftools. Instead we now simply hide/show the timeline when entering/leaving difftool (check https://github.com/TerriaJS/terriajs/blob/98cd1e3f9ab81d6ee57fb0f5d6ee2574d847f595/lib/ReactViews/Tools/DiffTool/DiffTool.tsx)

**Review by nf-s — APPROVED** [review]
🎉
