### PR TITLE
Tweak ArcGis WMS `getFeatureInfoFormat` default behaviour

### LINKED ISSUE #1222: GetFeatureInfo returning garbled response on Geoscience Australia's (ArcGis) WMSServer
Follows

- https://github.com/TerriaJS/nationalmap/issues/1150

## Example

> The “Topographic Map Indexes” layers being served through one of Geoscience Australia’s [ESRI ArcGis services](https://services.ga.gov.au/gis/services/Topographic_Map_Indexes/MapServer/WMSServer). 
> These are harvested through data.gov.au - https://data.gov.au/dataset/ds-ga-278de881-0d30-4465-af21-cb9046d97224/distribution/dist-ga-278de881-0d30-4465-af21-cb9046d97224-0/details?q=topographical
> 
> When making WMS GetFeatureInfo requests, we are receiving garbled output like this:
> 
>  image
> 
> The issue is the “info_format” parameter provided in GetFeatureInfo requests. The [GetCapabilities](https://services.ga.gov.au/gis/services/Topographic_Map_Indexes/MapServer/WMSServer?exceptions=XML&version=1.3.0&service=WMS&request=GetCapabilities) response for the WMSServer advertises that “text/html” is a valid value, but when it is used it returns the garbled response.
> If I use “application/vnd.esri.wms_raw_xml” instead, then I get a correct response.
> 
> Info_format = application/vnd.esri.wms_raw_xml
> https://services.ga.gov.au/gis/services/Topographic_Map_Indexes/MapServer/WMSServer?exceptions=XML&version=1.3.0&feature_count=101&styles=default&service=WMS&request=GetFeatureInfo&layers=General_Reference_Maps_Index_1Million&bbox=15654303.392804097%2C-3130860.6785608195%2C15967389.460660178%2C-2817774.6107047386&width=256&height=256&crs=EPSG%3A3857&query_layers=General_Reference_Maps_Index_1Million&info_format=application/vnd.esri.wms_raw_xml&i=181&j=165
> 
> Info_format =text/html
> https://services.ga.gov.au/gis/services/Topographic_Map_Indexes/MapServer/WMSServer?exceptions=XML&version=1.3.0&feature_count=101&styles=default&service=WMS&request=GetFeatureInfo&layers=General_Reference_Maps_Index_1Million&bbox=15654303.392804097%2C-3130860.6785608195%2C15967389.460660178%2C-2817774.6107047386&width=256&height=256&crs=EPSG%3A3857&query_layers=General_Reference_Maps_Index_1Million&info_format=text%2Fhtml&i=181&j=165

Because this data is harvested through data.gov.au - we can't change the `info_format`. We would have to change TerriaJS default behaviour of WMS, or we'd have to add some Trait on Ckan/Group to update `infoFormat` for matching URLs (eg `https://services.ga.gov.au/gis/services/***/MapServer/WMSServer`

### PR DESCRIPTION
**Pull request by nf-s**
### What this PR does

Fixes https://github.com/TerriaJS/nationalmap/issues/1222 https://github.com/TerriaJS/nationalmap/issues/1233 https://github.com/TerriaJS/terriajs/issues/6443

We have had a few issues with ArcGis MapServer WMS default `GetFeatureInfo` formats

- https://github.com/TerriaJS/nationalmap/issues/1222
- https://github.com/TerriaJS/nationalmap/issues/1233
- https://github.com/TerriaJS/terriajs/issues/6443

### Changes

- WMS `isEsri` default value will now check for case-insensitive `mapserver/wmsserver` (instead of `MapServer/WMSServer`)
- Tweak ArcGis MapServer WMS `GetFeatureInfo` default behaviour
  - Add `application/geo+json` and `application/vnd.geo+json` default `GetFeatureInfo` (after `application/json` in priority list)
  - Add `application/xml` default `GetFeatureInfo`. (if `isEsri` is true, then this will be used before `text/html`)

### Test me

- [Before Story](http://ci.terria.io/main/#share=s-gXKuKjchvZ2wHQO9xBZOXIqfRVY&configUrl=https://terria-catalogs-public.storage.googleapis.com/nationalmap/config/prod.json)
- [After Story](http://ci.terria.io/esri-wms-getfeatureformat/#share=s-gXKuKjchvZ2wHQO9xBZOXIqfRVY&configUrl=https://terria-catalogs-public.storage.googleapis.com/nationalmap/config/prod.json)

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [x] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/Catalog/Ows/WebMapServiceCapabilitiesStratum.ts [hunk 1]
```diff
@@ -852,10 +856,23 @@ export default class WebMapServiceCapabilitiesStratum extends LoadableStratum(
...
     if (formatsArray.includes("application/json"))
       return { format: "application/json", type: "json" };
+    if (formatsArray.includes("application/geo+json"))
+      return { format: "application/geo+json", type: "json" };
+    if (formatsArray.includes("application/vnd.geo+json"))
+      return { format: "application/vnd.geo+json", type: "json" };
+
+    // Special case for Esri WMS, use XML before HTML
+    // as HTML includes <table> with rowbg that is hard to read
+    if (this.isEsri && formatsArray.includes("text/xml")) {
```
Comment (mwu2018) [inline lib/Models/Catalog/Ows/WebMapServiceCapabilitiesStratum.ts:866]: The test of `this.isEsri` is redundant to the test at line 873.

**Comment by mwu2018** [comment]
Unable to do `After Story` test.
image

File: lib/Models/Catalog/Ows/WebMapServiceCapabilitiesStratum.ts (hunk 1 above)
Comment (nf-s) [reply lib/Models/Catalog/Ows/WebMapServiceCapabilitiesStratum.ts:866]: The test at 873 only applies for non-esri services - I haven't included `!this.isEsri` in the condition because it is superfluous 

The logic is this

- If service is ESRI, and supports use XML, use that
- For all services, if supports HTML, use that
- For all services, if supports GML, use that
- For all (non-ESRI) services, if supports XML, use that
- ...

This means for ESRI service, XML will be used before HTML and GML. 
But for non ESRI services, then HTML and GML will be used before XML

I have added a comment to clarify this

**Comment by nf-s** [comment]
> Unable to do `After Story` test. image

Sorry CI share credentials had expired - it is working now

**Review by mwu2018 — APPROVED** [review]
LGTM
