### PR TITLE
Fix issue #958 embedded czml

### LINKED ISSUE #958: Embedded CZML does not work
To reproduce:

Go to http://nationalmap.gov.au/#test
Expand test data -> CZML files, enable embedded CZML Files

screenshot

### PR DESCRIPTION
**Pull request by RacingTadpole**
Allow missing URLs in data, which allows eg. czml embedded in the init file to load. Added tests.
fixes #958

### CODE REVIEW

File: lib/Core/corsProxy.js [hunk 1]
```diff
@@ -23,6 +23,11 @@ var corsProxy = {
  * @return {Boolean} true if the proxy should be used, false if not.
  */
 corsProxy.shouldUseProxy = function(url) {
+    if (typeof url === 'undefined') {
```
Comment (kring) [inline lib/Core/corsProxy.js]: Use `!defined(url)` instead of `typeof url === 'undefined'`.

**Comment by kring** [comment]
Just the one minor nitpick! :)

**Comment by RacingTadpole** [comment]
Updated to use 'defined'
