### PR TITLE
Mobx: fix addedByUser

### LINKED ISSUE #3932: Model Architecture: wrong tab when previewing nested user added data items
Steps to reproduce

1. http://ci.terria.io/mobx/ > Explore Data > MyData > Add Web Data > add http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/mwq_gridAgg_P1A
2. Expand the newly added data group
3. Try to preview one of the nested items, e.g. number_of_observations

The item is previewed, but the tab changes to the Data Catalogue tab (rather than staying on the My Data tab).

### PR DESCRIPTION
**Pull request by mgcsls**
Reimplemented addedByUser to fix #3932.

### CODE REVIEW

File: lib/ModelMixins/GroupMixin.ts [hunk 1]
```diff
@@ -95,6 +95,13 @@ function GroupMixin<T extends Constructor<Model<GroupTraits>>>(Base: T) {
       } else {
         this.setTrait(stratumId, "members", [member.uniqueId]);
       }
+
+      if (
+        this.uniqueId !== undefined &&
+        member.knownContainerUniqueIds.indexOf(this.uniqueId) < 0
+      ) {
+        member.knownContainerUniqueIds.push(this.uniqueId);
```
Comment (soyarsauce) [inline lib/ModelMixins/GroupMixin.ts:103]: 💯

**Review by soyarsauce — COMMENTED** [review]
Awesome.
