### PR TITLE
Fix maximum call stack size exceeded on Math.min/max when creating Charts

### LINKED ISSUE #6941: Bug: Callstack exceeded in CalculateDomain when switching region aggregation
**Steps to reproduce**

1. Visit https://nationalmap.gov.au/#share=s-tkQhVRPh5p88SD55gbMYGdGq2IJ
2. Change _Building approvals by SA2 and above > Region type 3 times_
3. App crashes with following error:

```
3.TerriaMap.js:163 RangeError: Maximum call stack size exceeded
    at t.calculateDomain (3.TerriaMap.js:77:495048)
    at 3.TerriaMap.js:68:49236
    at Array.map (<anonymous>)
    at y.get (3.TerriaMap.js:68:48648)
    at et (3.TerriaMap.js:1:27840)
    at t.computeValue_ (3.TerriaMap.js:1:26050)
    at t.trackAndCompute (3.TerriaMap.js:1:25894)
    at t.get (3.TerriaMap.js:1:25130)
    at t.getObservablePropValue_ (3.TerriaMap.js:1:57896)
    at y.get (3.TerriaMap.js:1:62674)
```

### PR DESCRIPTION
**Pull request by nf-s**
### What this PR does

Fixes https://github.com/TerriaJS/terriajs/issues/6941

I also sneaked in a fix for `MyDataTab` showing a number.

image

### Test me

Make sure you test in Chrome (Firefox never had this issue)

- [Before link](http://ci.terria.io/main/#configUrl=https://terria-catalogs-public.storage.googleapis.com/nationalmap/config/prod.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22ZntTIvdp%22%3A%7B%22dereferenced%22%3A%7B%22isOpen%22%3Atrue%7D%2C%22knownContainerUniqueIds%22%3A%5B%22Root+Group%2FNational+Data+Sets%22%5D%2C%22type%22%3A%22terria-reference%22%7D%2C%22DPYjz1cT%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22ZntTIvdp%22%5D%2C%22type%22%3A%22sdmx-group%22%7D%2C%22DPYjz1cT%2Fdataflow-BA_SA2%22%3A%7B%22isOpenInWorkbench%22%3Atrue%2C%22currentTime%22%3A%222023-03-01T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%222016-07-01T00%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222023-07-01T00%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A1299049.4176470588%2C%22isPaused%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%5D%2C%22type%22%3A%22sdmx-json%22%7D%2C%22DPYjz1cT%2Fdataflow-BUILDING_ACTIVITY%22%3A%7B%22isOpenInWorkbench%22%3Afalse%2C%22show%22%3Afalse%2C%22currentTime%22%3A%222023-03-01T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%221980-06-30T14%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222022-12-31T13%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A3921842.1578947366%2C%22isPaused%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%5D%2C%22type%22%3A%22sdmx-json%22%7D%2C%22DPYjz1cT%2Fdataflow-CWD%22%3A%7B%22isOpenInWorkbench%22%3Afalse%2C%22show%22%3Afalse%2C%22currentTime%22%3A%222022-12-31T13%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%221986-06-30T14%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222023-03-31T13%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A3918052.75%2C%22isPaused%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%5D%2C%22type%22%3A%22sdmx-json%22%7D%2C%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2FcategoryScheme-INDUSTRY%22%5D%2C%22type%22%3A%22group%22%7D%2C%22DPYjz1cT%2FcategoryScheme-INDUSTRY%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%2C%22Root+Group%2FNational+Data+Sets%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22DPYjz1cT%2Fdataflow-BUILDING_ACTIVITY%22%2C%22DPYjz1cT%2Fdataflow-CWD%22%2C%22DPYjz1cT%2Fdataflow-BA_SA2%22%5D%2C%22timeline%22%3A%5B%22DPYjz1cT%2Fdataflow-BUILDING_ACTIVITY%22%2C%22DPYjz1cT%2Fdataflow-BA_SA2%22%5D%2C%22initialCamera%22%3A%7B%22west%22%3A144.23766092103352%2C%22south%22%3A-38.62318301158599%2C%22east%22%3A145.78797496812277%2C%22north%22%3A-36.97394756963962%2C%22position%22%3A%7B%22x%22%3A-4236664.753668559%2C%22y%22%3A2965132.3109916416%2C%22z%22%3A-3985220.617409384%7D%2C%22direction%22%3A%7B%22x%22%3A0.6471824166189727%2C%22y%22%3A-0.45294626934097404%2C%22z%22%3A0.6131839827566603%7D%2C%22up%22%3A%7B%22x%22%3A-0.5023695828733156%2C%22y%22%3A0.3515955046825979%2C%22z%22%3A0.7899401263960961%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223d%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.5%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Afalse%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-bing-aerial%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22pickedFeatures%22%3A%7B%22providerCoords%22%3A%7B%22https%3A%2F%2Ftiles.terria.io%2FSA2_2021%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.pbf%22%3A%7B%22x%22%3A923%2C%22y%22%3A627%2C%22level%22%3A10%7D%2C%22%2F%2Fdev.virtualearth.net%2F%22%3A%7B%22x%22%3A923%2C%22y%22%3A627%2C%22level%22%3A9%7D%7D%2C%22pickCoords%22%3A%7B%22lat%22%3A-37.69515389589726%2C%22lng%22%3A144.71644694058014%2C%22height%22%3A-0.19902188122299014%7D%2C%22current%22%3A%7B%22name%22%3A%22Fraser+Rise+-+Plumpton%22%2C%22hash%22%3A31240350743%7D%2C%22entities%22%3A%5B%5D%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)
- [After link](http://ci.terria.io/minmax-exceed-stack/#configUrl=https://terria-catalogs-public.storage.googleapis.com/nationalmap/config/prod.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22ZntTIvdp%22%3A%7B%22dereferenced%22%3A%7B%22isOpen%22%3Atrue%7D%2C%22knownContainerUniqueIds%22%3A%5B%22Root+Group%2FNational+Data+Sets%22%5D%2C%22type%22%3A%22terria-reference%22%7D%2C%22DPYjz1cT%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22ZntTIvdp%22%5D%2C%22type%22%3A%22sdmx-group%22%7D%2C%22DPYjz1cT%2Fdataflow-BA_SA2%22%3A%7B%22isOpenInWorkbench%22%3Atrue%2C%22currentTime%22%3A%222023-03-01T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%222016-07-01T00%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222023-07-01T00%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A1299049.4176470588%2C%22isPaused%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%5D%2C%22type%22%3A%22sdmx-json%22%7D%2C%22DPYjz1cT%2Fdataflow-BUILDING_ACTIVITY%22%3A%7B%22isOpenInWorkbench%22%3Afalse%2C%22show%22%3Afalse%2C%22currentTime%22%3A%222023-03-01T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%221980-06-30T14%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222022-12-31T13%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A3921842.1578947366%2C%22isPaused%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%5D%2C%22type%22%3A%22sdmx-json%22%7D%2C%22DPYjz1cT%2Fdataflow-CWD%22%3A%7B%22isOpenInWorkbench%22%3Afalse%2C%22show%22%3Afalse%2C%22currentTime%22%3A%222022-12-31T13%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%221986-06-30T14%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222023-03-31T13%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A3918052.75%2C%22isPaused%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%5D%2C%22type%22%3A%22sdmx-json%22%7D%2C%22DPYjz1cT%2Fcategory-BUILDING_CONSTRUCTION%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%2FcategoryScheme-INDUSTRY%22%5D%2C%22type%22%3A%22group%22%7D%2C%22DPYjz1cT%2FcategoryScheme-INDUSTRY%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22DPYjz1cT%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%2C%22Root+Group%2FNational+Data+Sets%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22DPYjz1cT%2Fdataflow-BUILDING_ACTIVITY%22%2C%22DPYjz1cT%2Fdataflow-CWD%22%2C%22DPYjz1cT%2Fdataflow-BA_SA2%22%5D%2C%22timeline%22%3A%5B%22DPYjz1cT%2Fdataflow-BUILDING_ACTIVITY%22%2C%22DPYjz1cT%2Fdataflow-BA_SA2%22%5D%2C%22initialCamera%22%3A%7B%22west%22%3A144.23766092103352%2C%22south%22%3A-38.62318301158599%2C%22east%22%3A145.78797496812277%2C%22north%22%3A-36.97394756963962%2C%22position%22%3A%7B%22x%22%3A-4236664.753668559%2C%22y%22%3A2965132.3109916416%2C%22z%22%3A-3985220.617409384%7D%2C%22direction%22%3A%7B%22x%22%3A0.6471824166189727%2C%22y%22%3A-0.45294626934097404%2C%22z%22%3A0.6131839827566603%7D%2C%22up%22%3A%7B%22x%22%3A-0.5023695828733156%2C%22y%22%3A0.3515955046825979%2C%22z%22%3A0.7899401263960961%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223d%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.5%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Afalse%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-bing-aerial%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22pickedFeatures%22%3A%7B%22providerCoords%22%3A%7B%22https%3A%2F%2Ftiles.terria.io%2FSA2_2021%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.pbf%22%3A%7B%22x%22%3A923%2C%22y%22%3A627%2C%22level%22%3A10%7D%2C%22%2F%2Fdev.virtualearth.net%2F%22%3A%7B%22x%22%3A923%2C%22y%22%3A627%2C%22level%22%3A9%7D%7D%2C%22pickCoords%22%3A%7B%22lat%22%3A-37.69515389589726%2C%22lng%22%3A144.71644694058014%2C%22height%22%3A-0.19902188122299014%7D%2C%22current%22%3A%7B%22name%22%3A%22Fraser+Rise+-+Plumpton%22%2C%22hash%22%3A31240350743%7D%2C%22entities%22%3A%5B%5D%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)
- Select "Region Type" = "Statistical Area Level 4"
- Select "Region Type" = "Statistical Area Level 2"
- Select "Region Type" = "Statistical Area Level 4" again
- It doesn't crash now
- Also go to "Upload" and see if there are "0"s on the screen

### Checklist

- [x] ~There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)~
- [ ] ~I've updated relevant documentation in `doc/`.~
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Core/math.ts
Comment (ljowen) [inline lib/Core/math.ts:1]: Could we just use `Math.min`? This method will be faster but I assume calculateDomain get's called only once per series

File: lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/MyDataTab.jsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ class MyDataTab extends React.Component {
   }
 
   render() {
-    const showTwoColumn = this.hasUserAddedData() & !this.state.activeTab;
+    const showTwoColumn = !!(this.hasUserAddedData() & !this.state.activeTab);
```
Comment (ljowen) [inline lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/MyDataTab.jsx]: Shouldn't this be a logical AND? 
```suggestion
    const showTwoColumn = !!(this.hasUserAddedData() && !this.state.activeTab);
```

Comment (nf-s) [reply lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/MyDataTab.jsx]: Absolutely! good find

File: lib/Core/math.ts
Comment (nf-s) [reply lib/Core/math.ts:1]: Do you mean using `Math.min` instead of `getMin`?
Or using `Math.min` instead of `min = nums[len] < min ? nums[len] : min;`

We can't use `Math.min` instead of `getMin` because of the spread operator in `calculateDomain`

- https://github.com/TerriaJS/terriajs/issues/6941#issuecomment-1790432094
- Sorry I forgot to link this in the ticket before

Comment (ljowen) [reply lib/Core/math.ts:1]: Aha! sorry I missed the actual root cause!

**Review by ljowen — APPROVED** [review]
