### PR TITLE
Fix Story Prompt

### LINKED ISSUE #6325: Story Prompt does not show when sharing a map that includes stories
image
This prompt should show when loading a map that includes stories.

### PR DESCRIPTION
**Pull request by staffordsmith83**
### What this PR does

Fixes #6325

When sharing a map with stories included, a 'stroy prompt' should show:
image

  
### Test me
  
Create a story in a map, and share it.
Open the share link.
The story prompt should show.

### Checklist

-   [y] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [y] I've updated relevant documentation in `doc/`.
-   [y] I've updated CHANGES.md with what I changed.
-   [y] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/Terria.ts [hunk 1]
```diff
@@ -533,6 +533,7 @@ export default class Terria {
   @observable depthTestAgainstTerrainEnabled = false;
 
   @observable stories: StoryData[] = [];
+  @observable storyPromptShown: number = 0;
```
Comment (na9da) [inline lib/Models/Terria.ts]: Might be good to leave a comment here on the purpose of this property.

Comment (tephenavies) [reply lib/Models/Terria.ts]: Definitely needs a comment. This sort of property should be on `ViewState` instead of `Terria`, but currently the origin of the scenes in `terria.stories` cannot be determined after it's been set.

Comment (staffordsmith83) [reply lib/Models/Terria.ts]: Added comment for this line. Cannot move to ViewState without a bigger fix I think

Comment (tephenavies) [reply lib/Models/Terria.ts]: Maybe sometime we'll fix story scene provenance (probably when we next extend stories, either with having a catalogue of stories for a map, or logging on to author official stories) and then we can get rid of this and detect loaded stories from outside Terria.ts.

**Review by tephenavies — APPROVED** [review]
