### PR TITLE
Fix app crash when rendering feature info with a custom title.

### LINKED ISSUE #1205: Click feature of Elevation dataset: LiDAR 25m DEM will trigger blank screen
### Click feature of Elevation dataset: LiDAR 25m DEM will trigger blank screen

Only happen to Elevation dataset: LiDAR 25m DEM
after the map is loaded, click the feature area (see 2nd screenshot)
If first click doesn’t trigger the blank screen, you might need click multiple times.

With exception:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PixelValue')
    at y.lookup (3.TerriaMap.js:91:1418)
    at g.escapedValue (3.TerriaMap.js:91:4523)
    at g.renderTokens (3.TerriaMap.js:91:3514)
    at g.render (3.TerriaMap.js:91:3215)
    at e.render (3.TerriaMap.js:91:5027)
    at o.value (3.TerriaMap.js:232:118218)
    at De (3.TerriaMap.js:15:7899)
    at 3.TerriaMap.js:15:121839
    at ye (3.TerriaMap.js:15:5804)
    at e.track (3.TerriaMap.js:15:17464)
```

image

image

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

Fixes https://github.com/TerriaJS/nationalmap/issues/1205

Currently the app crashes when rendering feature info with a custom title and the feature has no properties.
This PR fixes it.

### Test me

- Open this CI link for [main branch](http://ci.terria.io/main/#share=s-tWhZB0F2KjvwdJTDuJTFuIWVbXk&clean&https://gist.githubusercontent.com/na9da/af85c3eff23e1582f771b40e9f87a4da/raw/75104d5171d45c72b620168817193809c2325056/lidar.json)
- Click anywhere on the map layer for the workbench item
- Witness app crash
- Now repeat the same steps for [this branch](http://ci.terria.io/fix-feature-info-name/#share=s-tWhZB0F2KjvwdJTDuJTFuIWVbXk&clean&https://gist.githubusercontent.com/na9da/af85c3eff23e1582f771b40e9f87a4da/raw/75104d5171d45c72b620168817193809c2325056/lidar.json)
- The app does not crash

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/ReactViews/FeatureInfo/FeatureInfoSection.tsx [hunk 1]
```diff
@@ -396,7 +396,8 @@ export class FeatureInfoSection extends React.Component<FeatureInfoProps> {
     if (this.props.catalogItem.featureInfoTemplate.name) {
       title = Mustache.render(
         this.props.catalogItem.featureInfoTemplate.name,
-        this.featureProperties
+        this.mustacheContextData,
+        this.props.catalogItem.featureInfoTemplate.partials
```
Comment (na9da) [inline lib/ReactViews/FeatureInfo/FeatureInfoSection.tsx:400]: Need to pass all the template parameters like the other call [above](https://github.com/TerriaJS/terriajs/blob/5cc4472cd87196bb80e9317513e547f03ce6cc96/lib/ReactViews/FeatureInfo/FeatureInfoSection.tsx#L96-L100).

**Review by tephenavies — APPROVED** [review]
