### PR TITLE
Add support for `crs` property in GeoJSON `Feature` + Fix mvt highlight

### LINKED ISSUE #6141: Investigate and fix geometry highlight
It seems Terria lost the ability to highlight the geometry/areas selected for displaying feature information. 
To test: 
- https://maps.dea.ga.gov.au/#share=s-oG4tthYZPJqERzxG59OfgCPKYyk 
- https://maps.dea.ga.gov.au/#share=s-2xeD0MO1pptVEuGLudSDhx5HymU
- https://nationalmap.gov.au/#share=s-q1YZgyRn1nRM636RKf10rWsNyqX (note the Electoral boundaries are not highlighted but the Indigenous regions are)

### PR DESCRIPTION
**Pull request by nf-s**
### Add support for `crs` property in GeoJSON `Feature`

Fixes https://github.com/TerriaJS/terriajs/issues/6141

- Some WMS `GetFeatureInfo` requests will return a GeoJSON `Feature` with a `CRS` property. This was getting removed when we convert the `Feature` to `FeatureCollection` - which means the data wasn't getting reprojected.
- Added highlight feature support to `ProtomapsImageryProvider` for `mvt` datasets
  
### Test me

Open the following links and click on some features

#### WMS `GetFeatureInfo` with `CRS`

Only works after this PR

- http://ci.terria.io/main/#configUrl=https://nationalmap.gov.au/config.json&share=s-5zQKws8z5LINs4bJNXaA4Azy6hE
- http://ci.terria.io/geojson-feature-crs/#configUrl=https://nationalmap.gov.au/config.json&share=s-5zQKws8z5LINs4bJNXaA4Azy6hE

#### MVT polygons

Only works after this PR

- http://ci.terria.io/main/#configUrl=https://nationalmap.gov.au/config.json&share=s-m6raI1nesLMWALuzUp9myLledE5
- http://ci.terria.io/geojson-feature-crs/#configUrl=https://nationalmap.gov.au/config.json&share=s-m6raI1nesLMWALuzUp9myLledE5
  
#### GeoJSON lines

Both of these work

- http://ci.terria.io/main/#configUrl=https://nationalmap.gov.au/config.json&share=s-3UGQPnX9vCa9oIlRVadoygcmQeU
- http://ci.terria.io/geojson-feature-crs/#configUrl=https://nationalmap.gov.au/config.json&share=s-3UGQPnX9vCa9oIlRVadoygcmQeU

#### GeoJSON polygons

Both of these work

- http://ci.terria.io/main/#configUrl=https://nationalmap.gov.au/config.json&share=s-a7DkbrweMMzQ6uPeYFSGo2JVV0c
- http://ci.terria.io/geojson-feature-crs/#configUrl=https://nationalmap.gov.au/config.json&share=s-a7DkbrweMMzQ6uPeYFSGo2JVV0c

#### GeoSJON Points

Both of these work (no highlight, but feature properties will be shown)

- http://ci.terria.io/main/#configUrl=https://nationalmap.gov.au/config.json&share=s-nKpigfx0Dz2cwkA54utdszfz2iW
- http://ci.terria.io/geojson-feature-crs/#configUrl=https://nationalmap.gov.au/config.json&share=s-nKpigfx0Dz2cwkA54utdszfz2iW

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Map/ProtomapsImageryProvider.ts [hunk 1]
```diff
@@ -572,4 +583,87 @@ export default class ProtomapsImageryProvider
...
+      maximumZoom: options?.maximumZoom ?? this.maximumLevel,
+      maximumNativeZoom: options?.maximumNativeZoom,
+      rectangle: options?.rectangle ?? this.rectangle,
+      credit: options?.credit ?? this.credit,
+      paintRules: options?.paintRules ?? this.paintRules,
+      labelRules: options?.labelRules ?? this.labelRules
+    });
+  }
+
+  /** Duplicates ImageryProvider, and sets painRules to highlight picked features */
```
Comment (KeyboardSounds) [inline lib/Map/ProtomapsImageryProvider.ts]: paintRules? but I like painRules better.

**Review by KeyboardSounds — APPROVED** [review]
