### PR TITLE
Fix `shouldShorten` property in catalog and story `ShareUrl`

### LINKED ISSUE #6478: Story share url not shortening
the Story Share function does not shorten the share URL, but the Share function does
To test: 
- using TerriaJS 8.2.10 try creating a story with 3 scenes and then share the url; it's too long

### PR DESCRIPTION
**Pull request by nf-s**
### Fix `shouldShorten` property in catalog and story `ShareUrl`

Fixes https://github.com/TerriaJS/terriajs/issues/6478

Catalog and Story share URL was using `terria.getLocalProperty("shortenShareUrls")` to determine if share URL can be shortened - but this is not defined for most users.

It now uses `canShorten(terria)` if `terria.getLocalProperty("shortenShareUrls")` is undefined.

### Test me
  
- http://ci.terria.io/fix-share-shorten/
- Create story
- Click share in story panel
- See shortened URL

Then go into main share panel and toggle "Shorten the share URL using a web service"

The setting should be reflected in all share panels (eg from story or catalog) - and setting value should be preserved in local storage (eg after refreshing the page)

### Checklist

-   [ ] ~There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)~
-   [ ] ~I've updated relevant documentation in `doc/`.~
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/ReactViews/Map/Panels/SharePanel/SharePanel.tsx [hunk 1]
```diff
@@ -80,9 +79,8 @@ class SharePanel extends React.Component<PropTypes, SharePanelState> {
             terria={terria}
             viewState={viewState}
             includeStories={true}
-            shouldShorten={
-              !!terria.getLocalProperty("shortenShareUrls") ?? true
-            }
+            // Note we don't use terria.getLocalProperty("shortenShareUrls") here - as it is only configurable in SharePanelContent
+            shouldShorten={!!canShorten(terria)}
```
Comment (zoran995) [inline lib/ReactViews/Map/Panels/SharePanel/SharePanel.tsx]: Maybe check if local property is undefined and then use `canShorten` otherwise use local property value, so user choice doesn't get overridden?

**Review by tephenavies — APPROVED** [review]

File: lib/ReactViews/Map/Panels/SharePanel/SharePanel.tsx (hunk 1 above)
Comment (nf-s) [reply lib/ReactViews/Map/Panels/SharePanel/SharePanel.tsx]: Done!

**Review by mwu2018 — APPROVED** [review]
