### PR TITLE
Place a dot on map when expanding chart

### LINKED ISSUE #4856: Dots on map that showed where you clicked are missing in V8
### Expected behavior
When you click on a feature and expend the time series, you get a dot on the map that shows you where you have clicked, that relates to the colour of the line on the time series graph. That way, if you have loaded in multiple time series, you can see which one corresponds with which feature
image

### Actual behaviour
The dots and corresponding colour coordination of the time series graphs is missing from V8
image

### Steps to reproduce the behaviour
Load in 'Surface Water' > 'DEA Waterbodies', then click on a waterbody and hit 'expand'. Then click on a second waterbody and click 'expand'.

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

*Merge after #4866*

Fixes #4856 

* When expanding a chart from the feature info panel, this change places a colored dot on the map where the chart was generated from.
* Ensure that overlay data sources appear above workbench items.
* Refactors `ChartExpandAndDownloadButton` to `tsx`.

Test link: http://ci.terria.io/chart-expand-dots/#share=s-cj8JUoeGnXeGmaGW5FQebKUzniS

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: lib/ReactViews/Workbench/Controls/ChartItemSelector.jsx [hunk 1]
```diff
@@ -53,11 +55,13 @@ const ChartItemSelector = observer(function({ item }) {
   // discretelytimevarying items and have a separate chart button to enable/disable.
   const chartItems = chartView.chartItems
     .filter(c => c.item === item)
-    .filter(c => c.type !== "momentPoints" && c.type !== "momentLines");
+    .filter(c => c.type !== "momentPoints" && c.type !== "momentLines")
+    .sort((a, b) => (a.name >= b.name ? 1 : -1));
+
```
Comment (na9da) [inline lib/ReactViews/Workbench/Controls/ChartItemSelector.jsx:60]: Sort alphabetically by name. This ensures a stable order for chart item selectors not affected by the order of items in array trait that changes when some trait is set.

File: lib/ReactViews/Workbench/Controls/ChartItemSelector.jsx [hunk 2]
```diff
@@ -7,8 +7,10 @@ import ChartView from "../../../Charts/ChartView";
 import React from "react";
 import Chartable, { axesMatch } from "../../../Models/Chartable";
 
-const ChartItem = observer(({ item, chartItem }) => {
-  const lineColor = chartItem.getColor();
+export const ChartItem = observer(({ item, chartItem }) => {
+  const lineColor = chartItem.isSelectedInWorkbench
+    ? chartItem.getColor()
+    : "#fff";
```
Comment (na9da) [inline lib/ReactViews/Workbench/Controls/ChartItemSelector.jsx:13]: This is a text color should match the color of the chart line but if the line is unselected use a default color instead of "acquiring" a new color from the palette. This frees up the color for use by other active chart items.

File: lib/ReactViews/Custom/ChartCustomComponent.ts [hunk 3]
```diff
@@ -105,9 +114,8 @@ export interface ChartCustomComponentAttributes {
  *                   or  `<chart>[["x","y","z"],[1,10,3],[2,15,9],[3,8,12],[5,25,4]]</chart>`.
  */
 
-type CatalogMemberType = Model<CatalogMemberTraits>;
 export default abstract class ChartCustomComponent<
-  CatalogItemType extends CatalogMemberType
+  CatalogItemType extends Chartable
 > extends CustomComponent {
```
Comment (na9da) [inline lib/ReactViews/Custom/ChartCustomComponent.ts:119]: Had to make this `Chartable` to satisfy the types after refactoring `ChartExpandAndDownloadButtons` to `.tsx`

**Review by tephenavies — APPROVED** [review]
There's 1 suggestion to fix, then this can be merged.
