### PR TITLE
Fix zoom for satellite imagery in DEA maps

### LINKED ISSUE #4853: 'Ideal zoom' button zooms out waaaay too much for satellite data
### Expected behavior
N/A - this is a new V8 feature

### Actual behaviour
If you load in a satellite scene, then select 'ideal zoom', it zooms to an unhelpful map view
2D basemap:
image

3D basemap
image

### Steps to reproduce the behaviour
Load some satellite data, e.g. https://de-australia.prod.saas.terria.io/#share=s-t9qIomI0RVVey7AjNiIH4LMaXr7
Then select 'ideal zoom'

### PR DESCRIPTION
**Pull request by reginapramesti**
### What this PR does

Fixes #4853 

In master we perform some kind of "check" before zooming in (see [here](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CatalogItem.js#L1002)), to make sure that zooming doesn't break for datasets with bounding boxes that are overly large (or invalid), which is the underlying problem in the linked issue. The default zoom extent in such cases should be the `homeCamera` view (this is the behaviour in master). I am basically replicating that in mobx.

I added the code to `zoomTo` in `ViewingControls`, which seems like a weird place to add it. Though it allows me to _not_ have to add the code to both Leaflet and Cesium's `zoomTo`. The other alternative I thought of was to replace the `rectangle` property when it's first initialised in the catalogue item, but doing it this way allows me to _not_ have to do that for all catalogue items with `RectangleTraits` (ArcGis/WebMap/everything else that has `.rectangle`) so 🤷 

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: lib/ReactViews/Workbench/Controls/ViewingControls.jsx [hunk 1]
```diff
@@ -111,7 +111,16 @@ const ViewingControls = observer(
 
     zoomTo() {
       const viewer = this.props.viewState.terria.currentViewer;
-      viewer.zoomTo(this.props.item);
+      const item = this.props.item;
+      let zoomToView = item;
+      if (
+        item.rectangle !== undefined &&
+        item.rectangle.east - item.rectangle.west >= 360
```
Comment (rowanwins) [inline lib/ReactViews/Workbench/Controls/ViewingControls.jsx:118]: The only question mark I have about this is whether it will work for things in the Pacific that cross the anti-meridian...

Comment (reginapramesti) [reply lib/ReactViews/Workbench/Controls/ViewingControls.jsx:118]: I think if it does get to beyond 360 degrees from east to west there would still be something wrong with the bounding box, given that the only scenario this would break is if the east >= 180 and west <= -180, in which case the east should be the west value and vice versa and it seems like a weird bounding box anyway? 🤔 Though correct me if I'm wrong but I don't think it would break pacific map (as I imagine the behaviour in master doesn't break it either)

Comment (reginapramesti) [reply lib/ReactViews/Workbench/Controls/ViewingControls.jsx:118]: I'm thinking even in the worst case scenario where a bounding box has `east: 179.9` and `west`-179.9`, which is reasonably likely given the location of pacific islands 😂 , it still would zoom to the desired location

Comment (rowanwins) [reply lib/ReactViews/Workbench/Controls/ViewingControls.jsx:118]: Given that I can't find a good example and it's an edge case let's just role with what you've done :)

**Review by rowanwins — APPROVED** [review]
👍
