### PR TITLE
Fix theming regression

### LINKED ISSUE #7560: Theming regression
As of `v8.8.0` custom theming via sass no longer works.

**Steps to reproduce:**
- Checkout latest TerriaMap
- Modify the theme i.e.  add `$dark: red;` to `lib/Styles/variables.scss` in TerriaMap
- Changes are not passed in

From what I can tell neither `props.themeOverrides` is not being populated correctly in `StandardUserInterface` I suspect this is due to updating SaSS / Webpack

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #7560
 
Restores the `terriajs-variables` webpack alias while making it available through a sass @forward to minimise the scope change.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Review by na9da — APPROVED** [review]
Thanks for the fix @zoran995. 
Please remember to change terriamap CI branch back to `main` before you merge.

File: buildprocess/ci-deploy.sh [hunk 1]
```diff
@@ -22,7 +22,7 @@ npm install -g yarn@^1.19.0
 
 # Clone and build TerriaMap, using this version of TerriaJS
 TERRIAJS_COMMIT_HASH=$(git rev-parse HEAD)
-git clone -b main https://github.com/TerriaJS/TerriaMap.git
+git clone -b styles-test2 https://github.com/TerriaJS/TerriaMap.git
```
Comment (ljowen) [inline buildprocess/ci-deploy.sh]:
```suggestion
git clone -b main https://github.com/TerriaJS/TerriaMap.git
```
