### PR TITLE
Fix timefilter bug.

### LINKED ISSUE #6824: Share URL splitter comparing two different times of same layer - layer copy missing time controls
Using this fresh Share URL to compare two times from the same layer using the splitter: https://nationalmap.gov.au/#share=s-vurwfi7gP5EgpmsySTG6QBzqBa6

Note how the `copy` layer is missing the time controls:

Screenshot 2023-07-19 at 09 57 49

Where did the time controls go?

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

Fixes #6824 #6677 

- Fixes a bug when restoring time filter from a share link
- Simplifies overall code for picking imagery features from a location used by `TimeFilterMixin`
- Added more specs for time filter behaviour

#### Explanation:
Previously, when restoring the time filter from the co-ordinates, we:
  - pick all imagery providers on the map with the same base URL as that of the item
  - find one feature with matching time filter property 
  - this gave us the timestamps for the imagery available at the given co-ordinates. 
  
If we had 2 items, say `item1` and `item2` in the workbench with the same base URL but different layer names then we incorrectly resolved the time filter for both items to that of `item1`. This happened because in v8, the implementation only checked the URLs to map a picked feature to an item. In terriajs v7, we used to do an additional [comparison of the `imageryLayer`](https://github.com/TerriaJS/terriajs/blob/a6a2e6464cec91578b924728cdb3e3689b8c2794/lib/Models/ImageryLayerCatalogItem.js#L578) instance to make sure that we are using the time filter property for the correct layer. 

This PR fixes it by using a function that is local to the TimeFilterMixin and only picks the [imagery providers belonging to it](https://github.com/TerriaJS/terriajs/blob/dab991175a9b38f0f2ade26c6ed9018e10d72eec/lib/ModelMixins/TimeFilterMixin.ts#L107-L112).

### Test me

- Open this [test link](https://nationalmap.gov.au/#share=s-vurwfi7gP5EgpmsySTG6QBzqBa6) from issue #6824 
- Note how the copy layer (the first layer) is missing date filter
- Now open [the link](http://ci.terria.io/fix-time-filter-bug/#configUrl=https://terria-catalogs-public.storage.googleapis.com/nationalmap/config/prod.json&start={%22version%22%3A%228.0.0%22%2C%22initSources%22%3A[{%22stratum%22%3A%22user%22%2C%22models%22%3A{%22__User-Added_Data__%22%3A{%22isOpen%22%3Atrue%2C%22members%22%3A[%223a695d45-2f2f-4a3c-bd5e-dc704f648b72%22%2C%2214ea165c-95d2-4aaf-b927-042d99011be9%22]%2C%22knownContainerUniqueIds%22%3A[%22%2F%22]%2C%22type%22%3A%22group%22}%2C%226ATFM7CB%22%3A{%22dereferenced%22%3A{%22isOpen%22%3Atrue}%2C%22knownContainerUniqueIds%22%3A[%22Root+Group%2FNational+Data+Sets%22]%2C%22type%22%3A%22terria-reference%22}%2C%22CqkxcG%22%3A{%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A[%226ATFM7CB%22]%2C%22type%22%3A%22group%22}%2C%22SbBCvf%22%3A{%22show%22%3Afalse%2C%22isOpenInWorkbench%22%3Atrue%2C%22currentTime%22%3A%222023-07-08T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%222015-07-12T00%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222023-07-14T00%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A44856.818359375%2C%22isPaused%22%3Atrue%2C%22splitDirection%22%3A-1%2C%22timeFilterCoordinates%22%3A{%22latitude%22%3A-27.370431266344532%2C%22longitude%22%3A153.002927753145%2C%22height%22%3A107.76191109398104%2C%22tile%22%3A{%22x%22%3A947%2C%22y%22%3A592%2C%22level%22%3A10}}%2C%22knownContainerUniqueIds%22%3A[%22CqkxcG%22]%2C%22type%22%3A%22wms%22}%2C%22aN8xKz%22%3A{%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A[%22CqkxcG%22]%2C%22type%22%3A%22group%22}%2C%22rESkby%22%3A{%22currentTime%22%3A%222011-01-16T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%221986-08-16T00%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222011-11-17T00%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A57808.90838531844%2C%22isPaused%22%3Atrue%2C%22splitDirection%22%3A1%2C%22timeFilterCoordinates%22%3A{%22latitude%22%3A-27.382068820120537%2C%22longitude%22%3A153.132547070555%2C%22height%22%3A80.73945050241308%2C%22tile%22%3A{%22x%22%3A473%2C%22y%22%3A296%2C%22level%22%3A9}}%2C%22styles%22%3A%22true_colour%22%2C%22knownContainerUniqueIds%22%3A[%22aN8xKz%22]%2C%22type%22%3A%22wms%22}%2C%22x7b8dq%22%3A{%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A[%22CqkxcG%22]%2C%22type%22%3A%22group%22}%2C%2214ea165c-95d2-4aaf-b927-042d99011be9%22%3A{%22splitSourceItemId%22%3A%22SbBCvf%22%2C%22dereferenced%22%3A{%22show%22%3Atrue%2C%22name%22%3A%22DEA+Surface+Reflectance+(Sentinel-2)+(copy)%22%2C%22isOpenInWorkbench%22%3Atrue%2C%22currentTime%22%3A%222023-07-08T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%222015-07-12T00%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222023-07-14T00%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A44856.818359375%2C%22isPaused%22%3Atrue%2C%22splitDirection%22%3A-1%2C%22timeFilterCoordinates%22%3A{%22latitude%22%3A-27.370431266344532%2C%22longitude%22%3A153.002927753145%2C%22height%22%3A107.76191109355287%2C%22tile%22%3A{%22x%22%3A947%2C%22y%22%3A592%2C%22level%22%3A10}}}%2C%22knownContainerUniqueIds%22%3A[%22__User-Added_Data__%22]%2C%22type%22%3A%22split-reference%22}%2C%223a695d45-2f2f-4a3c-bd5e-dc704f648b72%22%3A{%22splitSourceItemId%22%3A%22rESkby%22%2C%22dereferenced%22%3A{%22show%22%3Afalse%2C%22name%22%3A%22DEA+Surface+Reflectance+(Landsat+5+TM)+(copy)%22%2C%22currentTime%22%3A%222011-01-16T00%3A00%3A00.000000000Z%22%2C%22startTime%22%3A%221986-08-16T00%3A00%3A00.000000000Z%22%2C%22stopTime%22%3A%222011-11-17T00%3A00%3A00.000000000Z%22%2C%22multiplier%22%3A57808.90838531844%2C%22isPaused%22%3Atrue%2C%22splitDirection%22%3A-1%2C%22timeFilterCoordinates%22%3A{%22latitude%22%3A-27.382068820120537%2C%22longitude%22%3A153.132547070555%2C%22height%22%3A80.739450503766%2C%22tile%22%3A{%22x%22%3A473%2C%22y%22%3A296%2C%22level%22%3A9}}%2C%22styles%22%3A%22true_colour%22}%2C%22knownContainerUniqueIds%22%3A[%22__User-Added_Data__%22]%2C%22type%22%3A%22split-reference%22}%2C%22%2F%22%3A{%22type%22%3A%22group%22}%2C%22Root+Group%2FNational+Data+Sets%22%3A{%22knownContainerUniqueIds%22%3A[%22%2F%22]%2C%22type%22%3A%22group%22}}%2C%22workbench%22%3A[%2214ea165c-95d2-4aaf-b927-042d99011be9%22%2C%22rESkby%22]%2C%22timeline%22%3A[]%2C%22initialCamera%22%3A{%22west%22%3A152.36627931962525%2C%22south%22%3A-27.852695357208294%2C%22east%22%3A153.51065245498222%2C%22north%22%3A-27.130497379405014%2C%22position%22%3A{%22x%22%3A-5119217.378521423%2C%22y%22%3A2615300.574449204%2C%22z%22%3A-2971887.812557948}%2C%22direction%22%3A{%22x%22%3A0.7899057479290899%2C%22y%22%3A-0.4035462461483423%2C%22z%22%3A0.4617351368567991}%2C%22up%22%3A{%22x%22%3A-0.4111836523686589%2C%22y%22%3A0.21006508665872492%2C%22z%22%3A0.8870178484065765}}%2C%22homeCamera%22%3A{%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8}%2C%22viewerMode%22%3A%223d%22%2C%22showSplitter%22%3Atrue%2C%22splitPosition%22%3A0.046703712296983765%2C%22settings%22%3A{%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-bing-aerial-with-labels%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse}%2C%22stories%22%3A[]}]}) for this branch with the fix
- See how the date time selectors are visible

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/GlobeOrMap.ts [hunk 1]
```diff
@@ -141,17 +133,6 @@ export default abstract class GlobeOrMap {
...
-   * Return features at a latitude, longitude and (optionally) height for the given imagery layers.
-   * @param latLngHeight The position on the earth to pick
-   * @param providerCoords A map of imagery provider urls to the tile coords used to get features for those imagery
-   * @returns A flat array of all the features for the given tiles that are currently on the map
-   */
-  abstract getFeaturesAtLocation(
-    latLngHeight: LatLonHeight,
-    providerCoords: ProviderCoordsMap
-  ): Promise<Entity[] | undefined> | void;
-
```
Comment (na9da) [inline lib/Models/GlobeOrMap.ts:154]: Not required anymore. Instead we moved the picking logic to [TimeFilterMixin](https://github.com/TerriaJS/terriajs/blob/dab991175a9b38f0f2ade26c6ed9018e10d72eec/lib/ModelMixins/TimeFilterMixin.ts#L113).

**Review by sixlighthouses — APPROVED** [review]
LGTM

**Comment by na9da** [comment]
Thanks for the review @sixlighthouses
