### PR TITLE
3263 chart sharing2

### LINKED ISSUE #3263: Charts - sharing doesn't work
Currently users can't share charts using the sharing url

test with AREMI https://www.nationalmap.gov.au/renewables/ 
1. Add Electricity - Generation - All generation types https://www.nationalmap.gov.au/renewables/#share=s-foZLkriqhpjoG3sm  
2. Select one of the generation points 
3. Expand the graph to either 1 or 7 days
4. Go to share/print, copy the url into another tab 
the chart is not visible in the shared page

### PR DESCRIPTION
**Pull request by soyarsauce**
Resolves #3263

### CODE REVIEW

File: lib/Models/TableStyle.js [hunk 1]
```diff
@@ -53,6 +53,12 @@ var TableStyle = function(options) {
    */
   this.dataVariable = options.dataVariable;
 
+  /**
+   * Whether all variables have been unselected
+   * @type {String}
+   */
+  this.allVariablesUnactive = options.allVariablesUnactive;
```
Comment (soyarsauce) [inline lib/Models/TableStyle.js:60]: I'm not sure if this is better as a computed value, I wanted to avoid any more interactions between tableStyle <-> tableStructure 😵 and thought it'd be simplest to set this on serialization.

**Review by chloeleichen — CHANGES_REQUESTED** [review]
Thanks @soyarsauce , it's working beautifully. Two things:

- [x] If you go to http://ci.terria.io/3263-chart-sharing2/#share=s-bpGkeCzWd9x5o8jijyHgVV2aBZ9, select both Power and Capacity from concept viewer, then generate share url. You'll see that only the state of Capacity is shared. Power is always off. And if you toggle Capacity off and share again, Capacity is automatically turned on. 

- [x] Chart from inline data doesn't get shared: http://ci.terria.io/3263-chart-sharing2/#share=s-2UijDVS1aKiIJyeXASii0PBhQ0A

File: lib/Models/CsvCatalogItem.js [hunk 2]
```diff
@@ -152,6 +181,39 @@ function loadTableFromCsv(item, csvString) {
   return item.initializeFromTableStructure(tableStructure);
 }
 
+/**
+ * Loads csv data from a URL into a (usually temporary) table structure.
+ * This is required by Chart.jsx for any non-csv format.
+ * @param  {String} url The URL.
```
Comment (kring) [inline lib/Models/CsvCatalogItem.js]: Outdated doc?

File: lib/Models/ChartDataGroup.js [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+/**
+ * A {@link CatalogGroup} representing a collection of layers for charting
+ *
+ * @alias ChartDataGroup
+ * @constructor
+ * @extends CatalogGroup
+ *
+ * @param {Terria} terria The Terria instance.
+ */
+var ChartDataGroup = function(terria) {
```
Comment (kring) [inline lib/Models/ChartDataGroup.js]: Do you need a separate type for this, versus a regular `CatalogGroup` with a known `id`?

File: lib/Models/Catalog.js [hunk 4]
```diff
@@ -214,13 +225,16 @@ Catalog.prototype._updateAndEnable = function(shareKey, itemJson) {
...
+  } else if (itemJson.isCsvForCharting === true && defined(itemJson.url)) {
+    return CsvCatalogItem.regenerateChartItem(itemJson, this.terria);
   } else {
     console.warn(
       "Share link has a catalog member with shareKey " +
         shareKey +
         " but could not find " +
         "this in the catalog"
     );
+    return when();
```
[the remark this answers is not in the document]
Comment (soyarsauce) [reply lib/Models/Catalog.js]: Old code, I was going down some other hole when debugging story sharing

File: lib/Core/addedForCharts.js [hunk 5]
```diff
@@ -0,0 +1,16 @@
+// import defined from "terriajs-cesium/Source/Core/defined";
+
+const CHART_DATA_CATEGORY_NAME = "Chart Data";
+
+// function addedForCharts(catalogMember) {
```
[the remark this answers is not in the document]
Comment (soyarsauce) [reply lib/Core/addedForCharts.js]: Removed!

File: lib/Models/CsvCatalogItem.js (hunk 2 above)
Comment (soyarsauce) [reply lib/Models/CsvCatalogItem.js]: Thanks, would have been confusing! I've updated

File: lib/Models/ChartDataGroup.js (hunk 3 above)
Comment (soyarsauce) [reply lib/Models/ChartDataGroup.js]: I thought early on it would have more chart specific behaviour, but it does not so I've reverted it back to a `CatalogGroup` for now 👍

**Comment by soyarsauce** [comment]
Concept toggling should be fully resolved now, I hope:
http://ci.terria.io/3263-chart-sharing2/#share=s-2WRkCci3oqX8NCGIKqu5L525ndw

@kring 

> Thanks @soyarsauce , it's working beautifully. Two things:
> 
> * [x]  If you go to http://ci.terria.io/3263-chart-sharing2/#share=s-bpGkeCzWd9x5o8jijyHgVV2aBZ9, select both Power and Capacity from concept viewer, then generate share url. You'll see that only the state of Capacity is shared. Power is always off. And if you toggle Capacity off and share again, Capacity is automatically turned on.
> * [x]  Chart from inline data doesn't get shared: http://ci.terria.io/3263-chart-sharing2/#share=s-2UijDVS1aKiIJyeXASii0PBhQ0A

**Comment by soyarsauce** [comment]
Oh and to highlight, the way inline chart sharing now works is saving the inlined data to dataUrl, but it only ever gets loaded with an overridden mime type of csv - is this sane?

**Review by chloeleichen — COMMENTED** [review]
Looks good. One thing, not a big deal, but if you toggle a concept and share again, the colors of the rest of the charting columns get reassigned, but it is a problem with chart and not this PR. 

Happy to merge it unless @kring have any other comments

File: lib/Models/TableCatalogItem.js [hunk 6]
```diff
@@ -634,32 +705,139 @@ TableCatalogItem.prototype._getValuesThatInfluenceLoad = function() {
...
+    );
+    return;
+  } else if (!defined(tableStructure)) {
+    console.error(
+      "syncAllVariablesUnactiveOnUpdate was called without a tableStructure?"
+    );
+    return;
+  }
+  if (!(tableStructure instanceof TableStructure)) {
+    console.error("table structure passed in isn't a TableStructure");
```
[the remark this answers is not in the document]
Comment (soyarsauce) [reply lib/Models/TableCatalogItem.js]: Thanks I didn't know we had those

**Review by chloeleichen — APPROVED** [review]
