### PR TITLE
Geojson/protomaps time-series support + fix mismatched IDs

### LINKED ISSUE #6918: Fix `ProtomapsImageryProvider` feature picking for time-series (GeoJson) lines and polygons
<details><summary>Example JSON (click to expand)</summary>
<code>
{
      "id": "time-based-automatic-styles",
      "type": "geojson",
      "geoJsonData": {
        "type": "FeatureCollection",
        "features": [
          {
            "type": "Feature",
            "properties": {
              "date": 2018,
              "someProperty": 3,
              "featureid": 0
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0130295753479, -37.77042639061412],
                  [145.0200891494751, -37.77042639061412],
                  [145.0200891494751, -37.76543949054887],
                  [145.0130295753479, -37.76543949054887],
                  [145.0130295753479, -37.77042639061412]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2019,
              "someProperty": 6,
              "featureid": 0
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0130295753479, -37.77042639061412],
                  [145.0200891494751, -37.77042639061412],
                  [145.0200891494751, -37.76543949054887],
                  [145.0130295753479, -37.76543949054887],
                  [145.0130295753479, -37.77042639061412]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2020,
              "someProperty": 10,
              "featureid": 0
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0130295753479, -37.77042639061412],
                  [145.0200891494751, -37.77042639061412],
                  [145.0200891494751, -37.76543949054887],
                  [145.0130295753479, -37.76543949054887],
                  [145.0130295753479, -37.77042639061412]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2021,
              "someProperty": 0,
              "featureid": 0
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0130295753479, -37.77042639061412],
                  [145.0200891494751, -37.77042639061412],
                  [145.0200891494751, -37.76543949054887],
                  [145.0130295753479, -37.76543949054887],
                  [145.0130295753479, -37.77042639061412]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2018,
              "someProperty": 3,
              "featureid": 1
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0100040435791, -37.76080849651723],
                  [145.00873804092407, -37.76342088777352],
                  [145.0157332420349, -37.76292895101701],
                  [145.0100040435791, -37.76080849651723]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2019,
              "someProperty": 4,
              "featureid": 1
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0100040435791, -37.76080849651723],
                  [145.00873804092407, -37.76342088777352],
                  [145.0157332420349, -37.76292895101701],
                  [145.0100040435791, -37.76080849651723]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2020,
              "someProperty": 1,
              "featureid": 1
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0100040435791, -37.76080849651723],
                  [145.00873804092407, -37.76342088777352],
                  [145.0157332420349, -37.76292895101701],
                  [145.0100040435791, -37.76080849651723]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2021,
              "someProperty": 10,
              "featureid": 1
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0100040435791, -37.76080849651723],
                  [145.00873804092407, -37.76342088777352],
                  [145.0157332420349, -37.76292895101701],
                  [145.0100040435791, -37.76080849651723]
                ]
              ]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "date": 2022,
              "someProperty": 7,
              "featureid": 1
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [145.0100040435791, -37.76080849651723],
                  [145.00873804092407, -37.76342088777352],
                  [145.0157332420349, -37.76292895101701],
                  [145.0100040435791, -37.76080849651723]
                ]
              ]
            }
          }
        ]
      },
      "styles": [
        {
          "id": "someProperty",
          "color": { "colorPalette": "Reds" },
          "time": { "timeColumn": "date", "idColumns": ["featureid"] },
          "hidden": false
        }
      ],
      "activeStyle": "someProperty"
    }
</code>
</details>

- [Test link](http://ci.terria.io/main/#clean&start=%7B%22initSources%22%3A%5B%7B%22homeCamera%22%3A%20%7B%22north%22%3A%20-8%2C%22east%22%3A%20158%2C%22south%22%3A%20-45%2C%22west%22%3A%20109%7D%2C%22workbench%22%3A%20%5B%22time-based-automatic-styles%22%5D%2C%22catalog%22%3A%20%5B%7B%22id%22%3A%20%22time-based-automatic-styles%22%2C%22type%22%3A%20%22geojson%22%2C%22geoJsonData%22%3A%20%7B%22type%22%3A%20%22FeatureCollection%22%2C%22features%22%3A%20%5B%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202018%2C%22someProperty%22%3A%203%2C%22featureid%22%3A%200%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0130295753479%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.77042639061412%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202019%2C%22someProperty%22%3A%206%2C%22featureid%22%3A%200%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0130295753479%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.77042639061412%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202020%2C%22someProperty%22%3A%2010%2C%22featureid%22%3A%200%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0130295753479%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.77042639061412%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202021%2C%22someProperty%22%3A%200%2C%22featureid%22%3A%200%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0130295753479%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.77042639061412%5D%2C%5B145.0200891494751%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.76543949054887%5D%2C%5B145.0130295753479%2C%20-37.77042639061412%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202018%2C%22someProperty%22%3A%203%2C%22featureid%22%3A%201%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0100040435791%2C%20-37.76080849651723%5D%2C%5B145.00873804092407%2C%20-37.76342088777352%5D%2C%5B145.0157332420349%2C%20-37.76292895101701%5D%2C%5B145.0100040435791%2C%20-37.76080849651723%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202019%2C%22someProperty%22%3A%204%2C%22featureid%22%3A%201%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0100040435791%2C%20-37.76080849651723%5D%2C%5B145.00873804092407%2C%20-37.76342088777352%5D%2C%5B145.0157332420349%2C%20-37.76292895101701%5D%2C%5B145.0100040435791%2C%20-37.76080849651723%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202020%2C%22someProperty%22%3A%201%2C%22featureid%22%3A%201%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0100040435791%2C%20-37.76080849651723%5D%2C%5B145.00873804092407%2C%20-37.76342088777352%5D%2C%5B145.0157332420349%2C%20-37.76292895101701%5D%2C%5B145.0100040435791%2C%20-37.76080849651723%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202021%2C%22someProperty%22%3A%2010%2C%22featureid%22%3A%201%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0100040435791%2C%20-37.76080849651723%5D%2C%5B145.00873804092407%2C%20-37.76342088777352%5D%2C%5B145.0157332420349%2C%20-37.76292895101701%5D%2C%5B145.0100040435791%2C%20-37.76080849651723%5D%5D%5D%7D%7D%2C%7B%22type%22%3A%20%22Feature%22%2C%22properties%22%3A%20%7B%22date%22%3A%202022%2C%22someProperty%22%3A%207%2C%22featureid%22%3A%201%7D%2C%22geometry%22%3A%20%7B%22type%22%3A%20%22Polygon%22%2C%22coordinates%22%3A%20%5B%5B%5B145.0100040435791%2C%20-37.76080849651723%5D%2C%5B145.00873804092407%2C%20-37.76342088777352%5D%2C%5B145.0157332420349%2C%20-37.76292895101701%5D%2C%5B145.0100040435791%2C%20-37.76080849651723%5D%5D%5D%7D%7D%5D%7D%2C%22styles%22%3A%20%5B%7B%22id%22%3A%20%22someProperty%22%2C%22color%22%3A%20%7B%20%22colorPalette%22%3A%20%22Reds%22%20%7D%2C%22time%22%3A%20%7B%20%22timeColumn%22%3A%20%22date%22%2C%20%22idColumns%22%3A%20%5B%22featureid%22%5D%20%7D%2C%22hidden%22%3A%20false%7D%5D%2C%22activeStyle%22%3A%20%22someProperty%22%7D%5D%2C%22viewerMode%22%3A%20%223dSmooth%22%2C%22baseMaps%22%3A%20%7B%22defaultBaseMapId%22%3A%20%22basemap-positron%22%2C%22previewBaseMapId%22%3A%20%22basemap-positron%22%7D%7D%5D%7D)
- Click through time-steps - styling is correct
- Click on feature - you get feature info for all timesteps
  - This is because `ProtomapsImageryProvider.pickFeatures` isn't time aware - it will return all features at a given point
  - In `GeoJsonMixin`, time is handled by not "painting" features (see [here](https://github.com/TerriaJS/terriajs/blob/53c6ecacb6df515c91ced9dd64fb6a64a9d089c1/lib/ModelMixins/GeojsonMixin.ts#L738-L742))

### PR DESCRIPTION
**Pull request by nf-s**
### Add geojson/protomaps time-series support

Fixes https://github.com/TerriaJS/terriajs/issues/6918 https://github.com/TerriaJS/terriajs/issues/6400 https://github.com/TerriaJS/terriajs/issues/6892

- Fix crash on empty GeoJSON features
- Add `tableFeatureInfoContext` support to `GeoJsonMixin.createProtomapsImageryProvider`
- Fix `GeoJsonMixin` timeline animation for lines/polygons
- Fix bug in mismatched GeoJSON Feature `_id_` and TableMixin `rowId` - this was causing incorrect styling when using `filterByProperties` or features had `null` geometry
- Fix splitter for `GeoJsonMixin` (lines and polygon features only)
- Fix share links with picked features from `ProtomapsImageryProvider`

### Test round 1

Links

- [Before](http://ci.terria.io/main/#clean&start=%7B%22initSources%22%3A%20%5B%7B%22catalog%22%3A%20%5B%7B%22name%22%3A%20%22geojson%20with%20time%22%2C%22type%22%3A%20%22geojson%22%2C%22url%22%3A%20%22http%3A%2F%2Fci.terria.io%2Fgeojson-timeseries%2Fbuild%2FTerriaJS%2Ftest%2FGeoJSON%2Ftime-based-automatic-styles.geojson%22%2C%22currentTime%22%3A%20%222018-01-01%22%2C%22defaultStyle%22%3A%20%7B%22time%22%3A%20%7B%20%22timeColumn%22%3A%20%22date%22%2C%20%22idColumns%22%3A%20%5B%22idProperty%22%5D%20%7D%7D%7D%5D%7D%5D%7D&share=s-nv1kOqSiaNqFYUcJRP6DbCFWFta)
- [After](http://ci.terria.io/geojson-timeseries/#clean&start=%7B%22initSources%22%3A%20%5B%7B%22catalog%22%3A%20%5B%7B%22name%22%3A%20%22geojson%20with%20time%22%2C%22type%22%3A%20%22geojson%22%2C%22url%22%3A%20%22http%3A%2F%2Fci.terria.io%2Fgeojson-timeseries%2Fbuild%2FTerriaJS%2Ftest%2FGeoJSON%2Ftime-based-automatic-styles.geojson%22%2C%22currentTime%22%3A%20%222018-01-01%22%2C%22defaultStyle%22%3A%20%7B%22time%22%3A%20%7B%20%22timeColumn%22%3A%20%22date%22%2C%20%22idColumns%22%3A%20%5B%22idProperty%22%5D%20%7D%7D%7D%5D%7D%5D%7D&share=s-nv1kOqSiaNqFYUcJRP6DbCFWFta)

Test the following

- Playing timeline should work now
- Splitter should work now
- Feature info will now show time-series chart

### Test round 1

Links

- [Before](http://ci.terria.io/main/#share=s-oYHit45GRC5I1MEFSYh7YSunhnU)
- [After](http://ci.terria.io/geojson-timeseries/#share=s-oYHit45GRC5I1MEFSYh7YSunhnU)

Test the following

- Click on the triangle
- Note that "Some Other Prop" is "what"
- But styling is incorrect on the first link
- Also test creating share links with picked features

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [x] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Map/ImageryProvider/ProtomapsImageryProvider.ts [hunk 1]
```diff
@@ -498,47 +514,48 @@ export default class ProtomapsImageryProvider
...
       this.source instanceof GeojsonSource &&
       this.source.geojsonObject
     ) {
+      // Get rough meters per pixel (at equator) for given zoom level
+      const zoomMeters = 156543 / Math.pow(2, level);
       // Create circle with 10 pixel radius to pick features
       const buffer = circle(
         [CesiumMath.toDegrees(longitude), CesiumMath.toDegrees(latitude)],
-        10 * this.terria.mainViewer.scale,
+        10 * zoomMeters,
```
Comment (nf-s) [inline lib/Map/ImageryProvider/ProtomapsImageryProvider.ts:558]: This change was required to fix share links with `pickedFeatures`.

When Terria was picking features on startup, `mainViewer.scale` was always equal to `1` - which meant sometimes features weren't being picked correctly.

Using the rough meters per pixel according to Web Mercator at the equator is not ideal - but the whole point of this is to allow some rough threshold to picking features without any mass (eg points or lines) - so I reckon it is ok

Comment (nf-s) [reply lib/Map/ImageryProvider/ProtomapsImageryProvider.ts:558]: If you don't trust my math - I sure don't - then you can verify using this table - https://wiki.openstreetmap.org/wiki/Zoom_levels

**Comment by nf-s** [comment]
@steve9164 this is ready for review, thanks!

**Review by tephenavies — APPROVED** [review]
