### PR TITLE
fix: splitter fails for local file catalog items

### LINKED ISSUE #7757: Error on compare vector data
Enabling "Compare" on a locally loaded vector layer (in this case, a GeoJSON polygon) gives the error shown below and the _"(copy)"_ layer is added, but without data.

Image

Image

The polygon code:
```
{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [ -73.958, 40.8003 ],
      [ -73.9498, 40.7968 ],
      [ -73.9737, 40.7648 ],
      [ -73.9814, 40.7681 ],
      [ -73.958, 40.8003 ] 
    ]]
  },
  "properties": {
    "name": "Example Polygon"
  }
}
```

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #7757

Store local file data as blob URLs in the URL trait instead of private instance fields, and follow the same approach already used for GLTF and Assimp catalogue items. This ensures duplicateModel() preserves the data since traits are copied during duplication. One potential downside of this approach is that we are currently not disposing the catalogue items from memory on remove (here is a ticket to track that https://github.com/TerriaJS/terriajs/issues/4816) 

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

**Comment by zoran995** [comment]
Deployment is failing due to the branch name

**Comment by zoran995** [comment]
This fixes the same bug as #7760, @ljowen, @na9da can you review and see which approach you think is better

**Comment by na9da** [comment]
Hi @zoran995 - both PRs look good to me.

One thing to check with this approach is whether it causes unnecessary duplication of memory because we are creating an object URL and then `fetching` from it again. My guess is the other strategy of keeping reference to the file might be slightly more memory efficient? You could use the devtools memory profiler to test the theory.

(here's a [sizable geojson](https://data.melbourne.vic.gov.au/explore/dataset/2023-building-footprints/export/) file for testing)

**Comment by zoran995** [comment]
@na9da, both branches have the same memory footprint, which matches my expectations. Both PRs will store the parsed result twice in memory, whereas the source file data is stored only once. URL.createObjectURL creates a pointer to a memory location where the data is stored. 
- In #7760, a duplicate will create a reference from the new item to the old item file and store it like that. Since it is added automatically to the map in `forceLoadMapItems` and `forceLoadGeojsonData`, it will parse that data.
- In this PR, it will create a memory pointer to data on initial load, and in `forceLoadMapItems` and `forceLoadGeojsonData`, it will parse data and store the parsed result as `_dataSource` or `_imageryProvider`.

File: lib/Models/Catalog/CatalogItems/CsvCatalogItem.ts [hunk 1]
```diff
@@ -54,22 +53,23 @@ export default class CsvCatalogItem
     return CsvCatalogItem.type;
   }
 
+  @action
   setFileInput(file: File) {
-    this._csvFile = file;
+    this.setTrait(
+      CommonStrata.user,
+      "url",
+      URL.createObjectURL(file) + "#" + file.name
```
Comment (na9da) [inline lib/Models/Catalog/CatalogItems/CsvCatalogItem.ts:61]: Nitpick: any reason to add the URI fragment, could this be a problem later when we implement revoking? Same for the other types.

File: test/Models/Catalog/CatalogReferences/SplitItemReferenceSpec.ts [hunk 2]
```diff
@@ -22,4 +24,39 @@ describe("SplitItemReference", function () {
...
+    const clone = splitRef.target;
+    expect(clone).toBeDefined();
+    expect(clone instanceof GeoJsonCatalogItem).toBe(true);
+
+    const cloneGeoJson = clone as GeoJsonCatalogItem;
+    expect(cloneGeoJson.url).toBe(sourceItem.url);
+    expect(HasLocalData.is(cloneGeoJson)).toBe(true);
+    if (HasLocalData.is(cloneGeoJson)) {
+      expect(cloneGeoJson.hasLocalData).toBe(true);
+    }
```
Comment (na9da) [inline test/Models/Catalog/CatalogReferences/SplitItemReferenceSpec.ts:61]: Recommendation: Should we add a manual revoke here?

**Review by na9da — APPROVED** [review]
Hi @zoran995 - thanks for testing the memory usage.

I've left a couple of minor comments.

File: lib/Models/Catalog/CatalogItems/CsvCatalogItem.ts (hunk 1 above)
Comment (zoran995) [reply lib/Models/Catalog/CatalogItems/CsvCatalogItem.ts:61]: GeoJSON uses it to determine if the file is zip so I used the same pattern

Comment (zoran995) [reply lib/Models/Catalog/CatalogItems/CsvCatalogItem.ts:61]: To revoke, we would need to split the URL at the hash, but we will need some registry for disposing of data, so when we add that, we can store it without fileName
