### PR TITLE
hide legend image if there is an error

### LINKED ISSUE #1773: Broken legend image symbol in newui
The Topography > ... > Aspect in AREMI shows like this in the new ui:

aremi aspect

In the old UI, there's no legend image.

old aspect

### PR DESCRIPTION
**Pull request by chloeleichen**
This fixes https://github.com/TerriaJS/terriajs/issues/1773

It makes the legend image behaves the same with the old UI: when there is an error loading the legend image, the image is hidden: 

screen shot 2016-07-20 at 4 44 24 pm

### CODE REVIEW

File: lib/ReactViews/Workbench/Controls/Legend.jsx [hunk 1]
```diff
@@ -17,6 +18,11 @@ const Legend = React.createClass({
 
     onImageError(legend) {
         legend.imageHasError = true;
+        this.forceUpdate();
+    },
+
+    componentWillMount() {
+        this.legends = this.getLegends();
```
Comment (kring) [inline lib/ReactViews/Workbench/Controls/Legend.jsx]: I think doing this on mount only will cause problems.  The list of legends may change asynchronously as the catalog item loads, and the UI needs to react to that.

File: lib/ReactViews/Workbench/Controls/Legend.jsx [hunk 2]
```diff
@@ -17,6 +18,11 @@ const Legend = React.createClass({
 
     onImageError(legend) {
         legend.imageHasError = true;
+        this.forceUpdate();
```
Comment (kring) [inline lib/ReactViews/Workbench/Controls/Legend.jsx]: I'd probably use knockout computed properties for this.  If you move the `this.props.item.legendUrls.map(...)` bit into the render function, and make it look something like this:

``` js
const legends = this.props.item.legendUrls.map(legendUrl => {
                 const legend = {
                     url: proxyCatalogItemUrl(this.catalogMember, legendUrl.url),
                     isImage: legendUrl.isImage(),
                     imageHasError: false,
                     onImageError: this.onImageError,
                      insertDirectly: !!legendUrl.safeSvgContent, // we only insert content we generated ourselves, not arbitrary SVG from init files.
                      safeSvgContent: {__html: legendUrl.safeSvgContent}
                  };
                  knockout.track(legend, ['imageHasError']);
                  return legend;
 });
```

The render should happen automatically if there's an error loading the image.

The only danger I can think of is the browser will try loading each legend again each time render is triggered.  The only really reliable way to fix that, though, is to put more of this state into the `LegendUrl` model object instead of keeping it in the UI.

**Comment by chloeleichen** [comment]
@kring can you have another look please?
