### PR TITLE
Fixed a bug in ArcGisMapServerCatalogItem

### LINKED ISSUE #7041: ArcGisMapServerCatalogItem should not use "pre-cached tiles" if a layer ID is specified in URL path.
Upload data to http://ci.terria.io/main from URL https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Administrative_Boundaries_Theme/MapServer/8 will result in error. 

***Note***
The logic is wrong at https://github.com/TerriaJS/terriajs/blob/b1b8753dac2b4fdfa4ef5fbe73bf4af6f0b8fb76/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L588

It should be something like

```
  usePreCachedTilesIfAvailable:
    !this.layers &&
    ( this.layersArray.length === 0 ||
      setsAreEqual(
        this.layersArray.map((l) => l.id),
        stratum.allLayers.map((l) => l.id)
      )
    ),
```

### PR DESCRIPTION
**Pull request by mwu2018**
### What this PR does

Fixes #7041 

### Test me
Open [before](http://ci.terria.io/main) or [after](http://ci.terria.io/issue-7041) in browser and upload data from URL https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Administrative_Boundaries_Theme/MapServer/8
then compare the results.
-  Before: Will not show boundaries in the map and will get many 404 errors in the dev tool panel.
-  After: Will show boundaries properly.

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts [hunk 1]
```diff
@@ -153,10 +153,17 @@ class MapServerStratum extends LoadableStratum(
...
+      // The following conditional code is commented out becasue
+      // the test will be true when the requested url path ends with
+      // layer ID. Overwriting "layers" will make "stratum.allLayers"
+      // contain single layer instead of all layers that were set
+      // previously from the base URI, causing unexpected errors.
+      //
+      // If layersMetadata is only a single layer -> shove into an array
+      // else if (isDefined(layersMetadataResponse?.id)) {
+      // layers = [layersMetadataResponse];
+      // }
```
Comment (nf-s) [inline lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts]: It might be better to remove the case where layers metadata is returned for a single layer.

This could be done by changing

https://github.com/TerriaJS/terriajs/blob/48f705486fde742dd8a9fcc743890b2179f7c590/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L113

to just

```ts
let layersUri = getBaseURI(item).segment("layers");
```

Then you can remove the entire block highlighted by this comment. 

This would mean that we get "detailed" layer metadata for all layers regardless of if layers have been specified (in the `url` or the `layers` trait) - which should fix the bug you found where `allLayers` only contained speciried layers

**Review by nf-s — CHANGES_REQUESTED** [review]
You have fixed the bug, but I wonder if it might be a better approach to entirely remove the case where layer metadata is fetched for a single layer.

Please see my comment below.

File: lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts (hunk 1 above)
Comment (nf-s) [reply lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts]: I am not entirely sure of the difference between "basic" and "detailed" layer metadata.

The "basic" layer metadata is the `layers` object in the MapServer service metadata. The "detailed" layer metadata is fetched by calling the `layers` MapServer endpoint.

https://github.com/TerriaJS/terriajs/blob/48f705486fde742dd8a9fcc743890b2179f7c590/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L149-L156

**Comment by mwu2018** [comment]
@nf-s Based on your comment, more lines are removed.

**Review by nf-s — APPROVED** [review]
Looks good, thanks Mike!
