### PR TITLE
Fix Feature Info display for CZML

### LINKED ISSUE #1260: CZML properties show as a JSON string in feature info panel
- Drag `withProperties.czml` from TerriaJS's `wwwroot/test/CZML` directory onto the map.
- Click on the small polygon near Canberra.

The feature info looks like this:

image

The CZML has a `properties` property that looks like this:

``` json
"properties": {
    "Type": "ABC",
    "Name": "Test",
    "Support table": {
        "value": [
            {
                "Capacity": "14.4",
                "Year": 2010
            },
            {
                "Capacity": "22.8",
                "Year": 2011
            },
            {
                "Capacity": "10.7",
                "Year": 2012
            }
        ]
    }
},
```

So I would expect it to render as a nicely-formatted table.

### LINKED ISSUE #1705: CZML Feature Info is broken in newui
There are the three CZML examples under #test. In the New UI:
- Embedded CZML - just shows the feature info panel with the feature name and no content.
- Large feature info box - works (yay! but oh no - this fails in the old UI now.)
- Simple test - as for embedded CZML

Also (per #1260) if you drag in `withProperties.czml` it shows the text "undefined".

image
image

image

Also, these seem to be treated as time-varying CZML, ie. they are updating every tick (with no change).

### PR DESCRIPTION
**Pull request by RacingTadpole**
Fixes #1705.
Fixes #1260 (in new UI at least).

Also added some specs, addressing a few of the items on #1686.

### CODE REVIEW

**Comment by RacingTadpole** [comment]
Oh wait - I need to fix the always-treating-properties-as-time-varying thing - don't merge this yet.

**Comment by RacingTadpole** [comment]
OK, ready for review now.

File: test/ReactViews/FeatureInfoSectionSpec.jsx [hunk 1]
```diff
@@ -25,25 +31,25 @@ if (typeof Intl === 'object' && typeof Intl.NumberFormat === 'function') {
 
 const contentClass = Styles.content;
 
-function getShallowRenderedOutput(jsx) {
-    const renderer = ReactTestUtils.createRenderer();
-    renderer.render(jsx);
-    return renderer.getRenderOutput();
-}
+// function getShallowRenderedOutput(jsx) {
```
Comment (kring) [inline test/ReactViews/FeatureInfoSectionSpec.jsx:34]: It'd be good to remove this commented-out code.  You can just do it in `newui`.
