### PR TITLE
Various tiny fixes for mobile view.

### LINKED ISSUE #5785: Mobile: make search location bar full width
IMG_2233 PNG

### LINKED ISSUE #5787: Mobile: search icon runs away from search box
IMG_2238 PNG

### LINKED ISSUE #5789: Mobile: Hide filter location option on Satellite Imagery
@AnaBelgun could you please add reproduction steps and screenshots to this ticket.

- Go to NationalMap 
- Select Satellite Imagery group 
- Select Satellite Images - 10m pixels - Sentinel 2 definitive - Sentinel 2A 
- Add to the map 
- Open the workbench view from the Eye button 
- Click "Filter by location" 
- A popup with "Select a point by clicking on the map" and "Cancel" appear
- You can only action the Cancellation because the map is obstructed by the workbench view 

image

### LINKED ISSUE #5791: Mobile stories: Stop the story text from covering the whole screen
Proposal to make the max height 50vh and make the story text body scrollable

### LINKED ISSUE #5806: Mobile: Initialize AR only when activated by user
Currently AR gets initialized and `deviceorientation` events are triggered even when the user hasn't activated the feature. Ideally AR initialization must be performed lazily.

https://github.com/TerriaJS/terriajs/blob/bf300939bd4ef9c98b970652f5643643e664c87e/lib/ReactViews/Map/Navigation/registerMapNavigations.tsx#L144-L148

### PR DESCRIPTION
**Pull request by na9da**
### What this PR does

- Fixes #5785 - to make search input field full width (Commit https://github.com/TerriaJS/terriajs/commit/3b696d8d27be94212faf10fce0d08797b937faf4)
- Automatically hide mobile modal window when user is interacting with the map. To fix #5789. (Commit https://github.com/TerriaJS/terriajs/pull/5800/commits/af0306c685bec5d33fd10dc9ad583ed6203912e2)
- Disables feature search in mobile (#5779)
- Disables export (clip&ship) in mobile (#5779) 
- Fixes #5787 - misplaced search bar icon in safari.
- Bind to `deviceorientation` only when AR is activated. Fixes #5806
- Make story panel height responsive so that it doesn't cover the entire screen on smaller devices (fixes #5791)

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: lib/Models/AugmentedVirtuality.ts [hunk 1]
```diff
@@ -62,20 +62,7 @@ export default class AugmentedVirtuality {
...
-    // currently support deviceorientationabsolute correctly: if
-    // ('ondeviceorientationabsolute' in window) {
-    // window.addEventListener('deviceorientationabsolute', function(event)
-    // {that._orientationUpdate(event);} ); } else
-    if ("ondeviceorientation" in window) {
-      window.addEventListener("deviceorientation", event =>
-        this.storeOrientation(event)
-      );
-    }
-  }
```
Comment (na9da) [inline lib/Models/AugmentedVirtuality.ts:78]: Moved this to `startEventLoop` method to avoid unnecessary changes even when AR is not activated by the user.

File: lib/ReactViews/Mobile/mobile-header.scss [hunk 2]
```diff
@@ -131,4 +131,7 @@
   }
 }
 
-@include empty-module("form-search-data");
+.formSearchData {
+  width: 90%;
+  margin: auto;
+}
```
Comment (na9da) [inline lib/ReactViews/Mobile/mobile-header.scss:137]: Makes mobile search bar full width.

File: lib/ReactViews/Story/story-panel.scss [hunk 3]
```diff
@@ -92,7 +92,13 @@
...
   color: $dark;
   font-size: 1rem;
-  max-height: 400px;
+  max-height: 100px;
+  @media (min-height: 700px) {
+    max-height: 200px;
+  }
+  @media (min-height: 900px) {
+    max-height: 400px;
+  }
```
Comment (na9da) [inline lib/ReactViews/Story/story-panel.scss:101]: Makes story panel content div responsive and avoids covering the whole screen on small devices.

File: lib/ReactViews/Workbench/Controls/ViewingControls.jsx [hunk 4]
```diff
@@ -341,7 +341,11 @@ const ViewingControls = observer(
             </li>
           </If>
           <If
-            condition={ExportableMixin.isMixedInto(item) && item.canExportData}
+            condition={
+              viewState.useSmallScreenInterface === false &&
+              ExportableMixin.isMixedInto(item) &&
+              item.canExportData
+            }
```
Comment (na9da) [inline lib/ReactViews/Workbench/Controls/ViewingControls.jsx:348]: Disable export option in mobile devices.

File: lib/ReactViews/Workbench/Controls/ViewingControls.jsx [hunk 5]
```diff
@@ -356,7 +360,11 @@ const ViewingControls = observer(
             </li>
           </If>
           <If
-            condition={SearchableItemMixin.isMixedInto(item) && item.canSearch}
+            condition={
+              viewState.useSmallScreenInterface === false &&
+              SearchableItemMixin.isMixedInto(item) &&
+              item.canSearch
+            }
```
Comment (na9da) [inline lib/ReactViews/Workbench/Controls/ViewingControls.jsx:367]: Disable feature search in mobile devices.

File: lib/ReactViews/Map/Navigation/MapNavigation.tsx [hunk 6]
```diff
@@ -289,9 +289,18 @@ class MapNavigation extends React.Component<PropTypes> {
...
           >
-            {items.map(item => (
-              <MapNavigationItem key={item.id} item={item} terria={terria} />
-            ))}
+            {items.map(item => {
+              // Do not expand in place for horizontal orientation
+              // as it results in buttons overlapping and hiding neighboring buttons.
+              return (
+                <MapNavigationItem
+                  expandInPlace={this.orientation !== Orientation.HORIZONTAL}
```
Comment (wibily) [inline lib/ReactViews/Map/Navigation/MapNavigation.tsx:298]: this seems a bit odd to me but eh, its better than overlapping i guess

**Review by wibily — APPROVED** [review]

File: lib/ReactViews/Map/Navigation/MapNavigation.tsx (hunk 6 above)
Comment (zoran995) [reply lib/ReactViews/Map/Navigation/MapNavigation.tsx:298]: This can cause an issue with buttons going of screen

Comment (na9da) [reply lib/ReactViews/Map/Navigation/MapNavigation.tsx:298]: That's a good point @zoran995 - I have filed an issue here https://github.com/TerriaJS/terriajs/issues/5847 and will bring it to @philipgrimmett's attention.

I think this is a better alternative than the current behavior so I'll go with this change for now until we have a more permanent fix.

Comment (zoran995) [reply lib/ReactViews/Map/Navigation/MapNavigation.tsx:298]: we can look into updating MapNavigation `computeSizes` and `updateNavigation`, to run in more cases (when buttons are expanded or similar), I perfectly fine with fixing this as part of #5847

Comment (wibily) [reply lib/ReactViews/Map/Navigation/MapNavigation.tsx:298]: I've added a small fix to add flex-wrap in the container which will at least make the icons appear on screen. However there is a bad interaction with hover if the expanded button is too big and wraps around. I've will add the detail into #5847
