### PR TITLE
fix process error types when obtaining user location

### LINKED ISSUE #3601: Geolocate button is broken is Safari
Attempting to centre the map based on your current location (geolocate) in Safari throws the following error (which isn't super helpful for users):

Screen Shot 2019-07-18 at 10 07 10 am

**Steps to reproduce**
1. https://nationalmap.gov.au
2. Click geolocate button on the map

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #3601

Process and provide more useful messages to the user. In safari, there is nothing more we can do, as there are numerous bugs reported on the internet, and it is actually sometimes it works and sometimes it doesn't.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/ReactViews/Map/MapNavigation/Items/MyLocation.ts [hunk 1]
```diff
@@ -57,6 +57,9 @@ export class MyLocation extends MapNavigationItemController {
         timeout: 5000,
         maximumAge: 0
       };
+      navigator.permissions.query({ name: "geolocation" }).then((result) => {
+        console.log(result);
```
Comment (pjonsson) [inline lib/ReactViews/Map/MapNavigation/Items/MyLocation.ts]: Does this log the result of each user location query to the console of the server? Aren't there potentially thousands of concurrent users?

Comment (zoran995) [reply lib/ReactViews/Map/MapNavigation/Items/MyLocation.ts]: Forgot to push changes, thanks. It would just log in browser but it is not needed and wouldn't change anything :D

Comment (pjonsson) [reply lib/ReactViews/Map/MapNavigation/Items/MyLocation.ts]: It seems I can't resolve this, but what I commented about seems fixed.

**Review by na9da — APPROVED** [review]
LGTM. Thanks @zoran995.

Custom error messages are an improvement over more technical browser messages.
