### PR TITLE
Fix add to map and tsx-ify some files

### LINKED ISSUE #5966: Timeline not enabled when adding an item to workbench using "Add to the map", and inconsistency with GA events fired on adding data
When adding a time varying item to the workbench by using "Add to the map" button in the catalog explorer, the timeline doesn't get enabled for some reason.

### PR DESCRIPTION
**Pull request by tephenavies**
### What this PR does

Fixes #5966.

Also:
- Remove unused overrideState
- Refactor toggle item of map code into separate file
- Typescriptify some DataCatalog jsx components
- Convert CatalogItem React component from scss to styled-components, fixing wrongly coloured catalog item names in maps with dynamic styles

Test with [this](http://ci.terria.io/fix-add-to-map/#configUrl=https://raw.githubusercontent.com/TerriaJS/saas-catalogs-public/main/terria-cube/map-config/prod.json) for:
* Adding a timeseries dataset to map from preview pane button opens timeline
* Colour is correct on hover on the catalog item names in the explorer panel

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

File: lib/ReactViews/DataCatalog/CatalogItem.jsx [hunk 1]
```diff
@@ -1,86 +0,0 @@
-import React from "react";
-import PropTypes from "prop-types";
-import classNames from "classnames";
-import Icon from "../../Styled/Icon";
-import PrivateIndicator from "../PrivateIndicator/PrivateIndicator";
-import { useTranslation } from "react-i18next";
-import defaultValue from "terriajs-cesium/Source/Core/defaultValue";
-
-import Styles from "./data-catalog-item.scss";
```
Comment (nf-s) [inline lib/ReactViews/DataCatalog/CatalogItem.jsx:9]: Can you delete this scss file now? I don't think it is used anywhere else

File: lib/ReactViews/DataCatalog/DataCatalogReference.tsx [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+        title={path}
+        btnState={
+          reference.isLoadingReference
+            ? ButtonState.Loading
+            : reference.isFunction
+            ? ButtonState.Stats
+            : ButtonState.Add
+        }
+        onBtnClick={reference.isFunction ? setPreviewedItem : add}
+      />
```
Comment (nf-s) [inline lib/ReactViews/DataCatalog/DataCatalogReference.tsx]: `btnState` is missing the `viewState.useSmallScreenInterface` check (in `DataCatalogItem.tsx`) - so on small/mobile screen interfaces we are seeing "(+)" (add button) for references, which change to ">" (set preview button) after loading

image

http://ci.terria.io/fix-add-to-map/#configUrl=https://nationalmap.gov.au/config.json&share=s-jnii2PJAvbbSxv93GtO1GHKfJhV

File: lib/ReactViews/DataCatalog/DataCatalogReference.tsx [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    if (defined(viewState.storyShown)) {
+      runInAction(() => {
+        viewState.storyShown = false;
+      });
+    }
+
+    if (
+      defined((reference as any).invoke) ||
```
Comment (nf-s) [inline lib/ReactViews/DataCatalog/DataCatalogReference.tsx]:
```suggestion
      CatalogFunctionMixin.isMixtedInto(reference) ||
```

File: lib/ReactViews/DataCatalog/DataCatalogReference.tsx (hunk 2 above)
Comment (nf-s) [reply lib/ReactViews/DataCatalog/DataCatalogReference.tsx]: Alternatively, I'm not sure if `DataCatalogItem` and `DataCatalogReference` need to be separate files, they have very similar code - but that can be left for another day when we tsxify `DataCatalogMember.jsx`, `DataCatalogGroup.jsx`, `CatalogGroup.jsx`...

I nearly think `DataCatalog*` could be merged into a single `DataCatalogMember` file - but it might get a bit crowded

**Review by nf-s — CHANGES_REQUESTED** [review]
❤️

**Review by nf-s — APPROVED** [review]

**Review by nf-s — CHANGES_REQUESTED** [review]
Oh wait I found an issue. I'll PM it to you

**Review by nf-s — APPROVED** [review]
❤️
