### PR TITLE
Fix WMS null rectangle check + inherit bbox from ancestor WMS `Layers`

### LINKED ISSUE #6860: WMS bbox doesn't inherit from parent `Layers`
when adding url https://gaez-services.fao.org/server/services/LR/ImageServer/WMSServer?request=GetCapabilities&service=WMS to a v8.3.2 terria via my-data > add-web-data, i'm able to select a layer, but when adding it to the map, get this error:

```
[mobx] uncaught error in 'Reaction[Autorun]' TypeError: Cannot read properties of undefined (reading 'east')
    at u.intersection (3.TerriaMap.js:6:147988)
    at F._createTileImagerySkeletons (3.TerriaMap.js:91:767661)
    at 3.TerriaMap.js:243:1663438
    at Rn.forEachLoadedTile (3.TerriaMap.js:243:1695526)
    at kt._onLayerAdded (3.TerriaMap.js:243:1663405)
    at i.raiseEvent (3.TerriaMap.js:6:77894)
    at bn.add (3.TerriaMap.js:243:1683346)
    at 3.TerriaMap.js:91:390978
    at u (3.TerriaMap.js:1:34610)
    at et (3.TerriaMap.js:1:27670)
```
Also tried adding it via a config file, with isEsri:true and/or crs:"epsg:4326", all failed. any guidance on using wms which does not support epsg:3857?

Thanx for checking, great work there on Terria!

### PR DESCRIPTION
**Pull request by nf-s**
### Fix WMS null rectangle check + inherit bbox from ancestor WMS `Layers`

Fixes https://github.com/TerriaJS/terriajs/issues/6860

There was a bug that was causing `WebMapServiceCatalogItem.rectangle` to be `{"west": 0,"south": 0,"east": 0,"north": 0}` which was breaking cesium internals. I fixed this with a null check.

Additionally, in the WMS spec (for both 1.3.0 and 1.1.1), you can have a hierarchy of `Layers` and certain parent properties can be inherited by child `Layers` - for example `EX_GeographicBoundingBox` - which is used to calculate `rectangle`. So I added ability to work up through `Layer` ancestors until a `EX_GeographicBoundingBox` is found.

In the test case below, the child `Layer` of interest doesn't have a `EX_GeographicBoundingBox`, but it's parent does - so it should inherit it.

**Changes**
- Add null check to `WebMapServiceCatalogItem` `rectangle` calculation - and now we ascend tree of WMS `Layers` until we find a rectangle.

### Test me

- On `main` [test link](http://ci.terria.io/main/#start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22homeCamera%22%3A%20%7B%22north%22%3A%20-8%2C%22east%22%3A%20158%2C%22south%22%3A%20-45%2C%22west%22%3A%20109%7D%2C%22catalog%22%3A%20%5B%7B%22url%22%3A%20%22https%3A%2F%2Fgaez-services.fao.org%2Fserver%2Fservices%2FLR%2FImageServer%2FWMSServer%3Frequest%3DGetCapabilities%26service%3DWMS%22%2C%22type%22%3A%20%22wms-group%22%2C%22name%22%3A%20%22Test%20WMS%22%7D%5D%2C%22viewerMode%22%3A%20%223dSmooth%22%2C%22baseMaps%22%3A%20%7B%22defaultBaseMapId%22%3A%20%22basemap-positron%22%2C%22previewBaseMapId%22%3A%20%22basemap-positron%22%7D%7D%5D%7D&share=s-uYaqG876u1nnKoCv50UYsMW0wxm)
- After fix [test link](http://ci.terria.io/wms-parent-rectangle/#start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22homeCamera%22%3A%20%7B%22north%22%3A%20-8%2C%22east%22%3A%20158%2C%22south%22%3A%20-45%2C%22west%22%3A%20109%7D%2C%22catalog%22%3A%20%5B%7B%22url%22%3A%20%22https%3A%2F%2Fgaez-services.fao.org%2Fserver%2Fservices%2FLR%2FImageServer%2FWMSServer%3Frequest%3DGetCapabilities%26service%3DWMS%22%2C%22type%22%3A%20%22wms-group%22%2C%22name%22%3A%20%22Test%20WMS%22%7D%5D%2C%22viewerMode%22%3A%20%223dSmooth%22%2C%22baseMaps%22%3A%20%7B%22defaultBaseMapId%22%3A%20%22basemap-positron%22%2C%22previewBaseMapId%22%3A%20%22basemap-positron%22%7D%7D%5D%7D&share=s-uYaqG876u1nnKoCv50UYsMW0wxm)

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] ~I've updated relevant documentation in `doc/`.~
- [x] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/Catalog/Ows/WebMapServiceCapabilities.ts [hunk 1]
```diff
@@ -132,7 +132,7 @@ type Mutable<T> = { -readonly [P in keyof T]: T[P] };
 export function getRectangleFromLayer(
   layer: CapabilitiesLayer
 ): StratumFromTraits<RectangleTraits> | undefined {
-  var egbb = layer.EX_GeographicBoundingBox; // required in WMS 1.3.0
+  var egbb = layer?.EX_GeographicBoundingBox; // required in WMS 1.3.0
```
Comment (na9da) [inline lib/Models/Catalog/Ows/WebMapServiceCapabilities.ts]: If the `layer` can be `undefined`, it is not reflected in the type here. Do we really need `layer?.`?

**Review by na9da — APPROVED** [review]
@nf-s - the changes look good to me. 

Just left a small comment.
Also, please remember to move change under the new version header in CHANGES.md.

File: lib/Models/Catalog/Ows/WebMapServiceCapabilities.ts (hunk 1 above)
Comment (nf-s) [reply lib/Models/Catalog/Ows/WebMapServiceCapabilities.ts]: Good point! I have removed the optional chaining
