### PR TITLE
fix: wms get feature info with projection

### LINKED ISSUE #5057: Incorrect Feature Info panel lat/lon on WMS Point data
Consider https://nationalmap.gov.au/ and add external WMS of https://gs.geoscience.nsw.gov.au/geoserver/ows

Add layer "NSW Drillhole"

I have shared this here https://nationalmap.gov.au/#share=s-ko2gHxva9VKD7RY0UtDSDHOFNxf

Clicking on the points, the lat/lon in the feature panel are not correct.

image

I am not suggesting this is a specific issue with the NSW Geoscience WMS. I needed a WMS vector point source and couldn't find one in the National Map catalogue. We are seeing the same problems on our in-house GeoServer.

http://ci.terria.io/master/ and http://ci.terria.io/next/ similarly afflicted. https://map.terria.io/ (suitably ancient) also not good.

I think .csv and Esri MapServer are ok.

Advice is invited.

### PR DESCRIPTION
**Pull request by zoran995**
### What this PR does

Fixes #5057, #7700

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

### CODE REVIEW

File: lib/Models/Catalog/Ows/WebMapServiceCatalogItem.ts [hunk 1]
```diff
@@ -818,4 +841,40 @@ export function formatDimensionsForOws(
   );
 }
 
+function geoJsonToFeatureInfoWithProject(
```
Comment (na9da) [inline lib/Models/Catalog/Ows/WebMapServiceCatalogItem.ts:846]: Might be good to add a comment to describe what the function does and link back to [the source](https://github.com/CesiumGS/cesium/blob/5754031f65646bee5f9d0e9a56dec7d3677a8b08/packages/engine/Source/Scene/GetFeatureInfoFormat.js#L74)

**Review by na9da — APPROVED** [review]
Looks good @zoran995. Just a minor suggestion
